(() => {
  const STRIPE='https://buy.stripe.com/bJe14p2QV1M13dz5kjcV208';
  const KEY='nw_pro_cold_email_requirement_checker';
  const $=(id)=>document.getElementById(id);
  const isPro=()=>localStorage.getItem(KEY)==='1'||!!localStorage.getItem('nw_pro_key');
  const lang=()=>document.documentElement.lang==='en'?'en':'ja';
  function activate(){const u=new URL(location.href);if(u.searchParams.get('pro')==='1'){localStorage.setItem(KEY,'1');u.searchParams.delete('pro');history.replaceState({},'',u.toString())}}
  function toast(m){let e=$('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
  function needPro(){if(isPro())return true;toast(lang()==='ja'?'Pro限定機能です。購入後に ?pro=1 で解放してください。':'Pro feature locked. Reopen with ?pro=1 after purchase.');render();return false}
  function words(s){return String(s||'').trim().split(/\s+/).filter(Boolean).length}
  function lines(s){return String(s||'').split('\n').map(x=>x.trim()).filter(Boolean)}
  function md(){const a=$('emailText')?.value||'';const b=$('proDraftB')?.value||'';const subj=$('emailSubject')?.value||'';return ['# Cold Email Pro Review','',`Subject: ${subj}`,'', '## Draft A stats',`- Characters: ${a.length}`,`- Words/segments: ${words(a)}`,`- Lines: ${lines(a).length}`,'','## Draft B stats',`- Characters: ${b.length}`,`- Words/segments: ${words(b)}`,`- Lines: ${lines(b).length}`,'','## Draft A',a,'','## Draft B',b,'','## Note','This is a structure review aid. It does not guarantee legal compliance, deliverability, reply rate, or sales results.'].join('\n')}
  function download(name,text){const blob=new Blob([text],{type:'text/markdown;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  function setProVisibility(){const pro=isPro();const score=$('scoreValue')?.closest('.result-card');if(score)score.style.display=pro?'':'none';const sug=$('suggestions')?.closest('.field');if(sug)sug.style.display=pro?'':'none';const status=$('overallStatus');if(status&&!pro)status.textContent=lang()==='ja'?'無料チェックリスト利用中 — スコアと改善候補はPro':'Free checklist mode — score and suggestions are Pro';}
  function buildBox(){if($('coldProBox'))return;const root=$('toolRoot');if(!root)return;const box=document.createElement('section');box.id='coldProBox';box.className='nw-note';box.innerHTML=`<strong>Pro</strong><p id="coldProMsg"></p><p><a class="btn primary" href="${STRIPE}" target="_blank" rel="noopener">Unlock Pro / Proを購入</a></p><p class="nw-muted">After payment, open this page with <code>?pro=1</code>.</p><div class="field"><label class="label" for="proDraftB">Pro: Draft B compare</label><textarea id="proDraftB" class="textarea" placeholder="Paste a second draft for comparison"></textarea></div><div class="row"><button id="proCompareBtn" class="btn" type="button">Pro: Compare drafts</button><button id="proExportBtn" class="btn" type="button">Pro: Export Markdown</button></div><pre id="proCompareOut" class="out"></pre>`;root.appendChild(box);$('proCompareBtn').addEventListener('click',()=>{if(!needPro())return;const a=$('emailText')?.value||'',b=$('proDraftB')?.value||'';$('proCompareOut').textContent=['Draft comparison',`A: ${a.length} chars / ${words(a)} words`, `B: ${b.length} chars / ${words(b)} words`, `Difference: ${Math.abs(a.length-b.length)} chars`].join('\n')});$('proExportBtn').addEventListener('click',()=>{if(!needPro())return;download('cold-email-pro-review.md',md())})}
  function render(){buildBox();const msg=$('coldProMsg');if(msg)msg.textContent=isPro()?'Pro active: score, suggestions, draft compare, and Markdown export are unlocked. / Pro解放済み。':'Pro locks score, suggestions, draft compare, and Markdown export. / Proでスコア・改善候補・比較・保存を解放。';setProVisibility();document.body.classList.toggle('is-pro',isPro())}
  function init(){activate();const timer=setInterval(()=>{if($('toolRoot')&&$('emailText')){clearInterval(timer);render();const root=$('toolRoot');new MutationObserver(render).observe(root,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(render,0));}},100)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
