(() => {
  const STRIPE='https://buy.stripe.com/bJe14p2QV1M13dz5kjcV208';
  const KEY='nw_pro_incident_update_generator';
  const $=(id)=>document.getElementById(id);
  const $$=(s)=>Array.from(document.querySelectorAll(s));
  const isPro=()=>localStorage.getItem(KEY)==='1'||!!localStorage.getItem('nw_pro_key');
  const lang=()=>document.documentElement.lang==='en'?'en':'ja';
  let made=false;
  function activate(){const u=new URL(location.href);if(u.searchParams.get('pro')==='1'){localStorage.setItem(KEY,'1');u.searchParams.delete('pro');history.replaceState({},'',u.toString())}}
  function applyLang(l){$$('[data-i18n]').forEach(e=>e.style.display=e.dataset.i18n===l?'':'none');$$('.nw-lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));document.documentElement.lang=l;localStorage.setItem('nw_lang',l);proBox()}
  function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
  function v(id){return ($(id)?.value||'').trim()}
  function make(l,a,d){const ja=l==='ja';const s=d.status||'Investigating';const title=ja?{customer:'顧客向け',internal:'社内向け',social:'SNS向け'}[a]:{customer:'Customer',internal:'Internal',social:'Social'}[a];const rows=[ja?`【${title} / ${s}】`:`[${title} / ${s}]`,ja?`${d.service}の更新です。現在の状態は${s}です。`:`Update for ${d.service}. Current status: ${s}.`,'',(ja?'影響: ':'Impact: ')+d.impact,(ja?'次回更新: ':'Next update: ')+d.next];[['start',ja?'開始: ':'Start: '],['comp',ja?'対象: ':'Components: '],['action',ja?'対応: ':'Actions: '],['recovery',ja?'復旧: ':'Recovery: '],['duration',ja?'期間: ':'Duration: '],['cause',ja?'概要: ':'Summary: '],['follow',ja?'次対応: ':'Follow-up: ']].forEach(([k,label])=>{if(d[k])rows.push(label+d[k])});rows.push('',ja?'公開前に内容を確認してください。':'Review before publishing.');return rows.join('\n')}
  function data(){return{service:v('service'),status:v('status'),impact:v('impact'),next:v('nextUpdate'),start:v('startTime'),comp:v('components'),action:v('mitigation'),recovery:v('recoveryTime'),duration:v('duration'),cause:v('causeSummary'),follow:v('followUpPlan')}}
  function set(id,t){const e=$(id);if(e)e.textContent=t}
  function all(){return['outputCustomerJa','outputInternalJa','outputSocialJa','outputCustomerEn','outputInternalEn','outputSocialEn'].map(id=>$(id)?.textContent||'').join('\n\n---\n\n')}
  function dl(n,t,type='text/plain;charset=utf-8'){const b=new Blob([t],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),800)}
  async function copy(t){try{await navigator.clipboard.writeText(t);toast(lang()==='ja'?'コピーしました。':'Copied.')}catch(_){toast('Copy failed')}}
  function proBox(){if(!$('nwProBox')){const s=document.createElement('section');s.id='nwProBox';s.className='nw-note';s.innerHTML=`<strong>Pro</strong><p id="nwProMsg"></p><p><a class="btn primary" href="${STRIPE}" target="_blank" rel="noopener">Unlock Pro / Proを購入</a></p><p class="nw-muted">After payment, open this page with ?pro=1.</p>`;document.querySelector('main')?.insertBefore(s,document.querySelector('main .card')?.nextSibling||null)}$('nwProMsg').textContent=isPro()?'Pro active: Markdown pack export is unlocked. / Pro解放済み。':'Pro locks Markdown pack export. / ProでMarkdownパック保存を解放。'}
  function needPro(){if(isPro())return true;proBox();toast(lang()==='ja'?'Pro限定機能です。購入後に ?pro=1 で解放してください。':'Pro feature locked. Reopen with ?pro=1 after purchase.');return false}
  function gen(){const d=data();if(!d.service||!d.impact||!d.next){toast(lang()==='ja'?'必須項目を入力してください。':'Fill in required fields.');return}set('outputCustomerJa',make('ja','customer',d));set('outputInternalJa',make('ja','internal',d));set('outputSocialJa',make('ja','social',d));set('outputCustomerEn',make('en','customer',d));set('outputInternalEn',make('en','internal',d));set('outputSocialEn',make('en','social',d));made=true;$$('[data-copy]').forEach(b=>b.disabled=false);$('downloadBtn').disabled=false;toast(lang()==='ja'?'生成しました。':'Generated.')}
  function init(){activate();let l=(navigator.language||'').toLowerCase().startsWith('ja')?'ja':'en';try{const s=localStorage.getItem('nw_lang');if(s==='ja'||s==='en')l=s}catch(_){}$$('.nw-lang-switch button').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.lang)));applyLang(l);$('generateBtn').addEventListener('click',gen);$$('[data-copy]').forEach(b=>b.addEventListener('click',()=>{if(!made)return toast('Generate first');const aud=b.dataset.copy;const id='output'+aud[0].toUpperCase()+aud.slice(1)+(lang()==='ja'?'Ja':'En');copy($(id).textContent)}));$('downloadBtn').addEventListener('click',()=>{if(!made)return toast('Generate first');const aud=v('audience')||'customer';const id='output'+aud[0].toUpperCase()+aud.slice(1)+(lang()==='ja'?'Ja':'En');dl('update.txt',$(id).textContent)});const btn=document.createElement('button');btn.className='btn';btn.type='button';btn.textContent='Pro: Save Markdown pack';btn.addEventListener('click',()=>{if(!needPro())return;if(!made)return toast('Generate first');dl('update-pro.md','# Pro Update Pack\n\n'+all(),'text/markdown;charset=utf-8')});$('downloadBtn').parentNode.appendChild(btn);proBox()}
  document.addEventListener('DOMContentLoaded',init);
})();
