(() => {
  const isEn = /\/manual-finder\/en\/?/.test(location.pathname);
  const base = isEn ? ".." : ".";
  const FULL = `${base}/data/manuals.full.js?v=mf500-paged-20260513b`;
  const JSON_URL = `${base}/data/manuals.json`;
  const S = { all: [], filtered: [], page: 1, per: 48, lang: isEn ? "en" : "ja" };
  const $ = (id) => document.getElementById(id);
  const E = {
    results: $("results"), count: $("resultCount"), status: $("loadStatus"), q: $("searchInput"), cat: $("categorySelect"), quick: $("quickButtons"),
    emptyJa: $("emptyMessage"), emptyEn: $("emptyMessageEn"), i18n: document.querySelectorAll("[data-i18n]"), langBtns: document.querySelectorAll(".nw-lang-switch button")
  };
  const t = (ja, en) => S.lang === "ja" ? ja : en;
  const norm = (v) => String(v || "").trim().toLowerCase();
  const loadScript = (src) => new Promise((resolve, reject) => { const s = document.createElement("script"); s.src = src; s.onload = resolve; s.onerror = reject; document.head.appendChild(s); });
  function normalize(rows) {
    const seen = new Set();
    return (rows || []).filter(Boolean).map((x) => {
      const brand = x.brand || x.nameEn || x.nameJa || "Unknown";
      const category = x.category || "その他";
      return { brand, nameJa: x.nameJa || brand, nameEn: x.nameEn || brand, category, country: x.country || "Global", manualUrl: x.manualUrl || x.supportUrl || "", supportUrl: x.supportUrl || x.manualUrl || "", note: x.note || "公式マニュアル／サポート入口です。", hint: x.hint || `${brand} 型番、製品名、シリーズ名`, tags: Array.isArray(x.tags) ? x.tags : String(`${brand} ${category}`).toLowerCase().split(/\s+/), linkReview: x.linkReview || "official entry" };
    }).filter((x) => { const key = `${x.brand}|${x.category}`.toLowerCase(); if (seen.has(key)) return false; seen.add(key); return true; });
  }
  function searchText(x) { return [x.brand, x.nameJa, x.nameEn, x.category, x.country, x.note, x.hint, ...(x.tags || [])].join(" ").toLowerCase(); }
  function lang(lang) { S.lang = lang; E.i18n.forEach((n) => { const c = n.getAttribute("data-i18n"); if (c) n.hidden = c !== lang; }); E.langBtns.forEach((b) => b.classList.toggle("active", b.getAttribute("data-lang") === lang)); render(); }
  function stylePager() { if (document.getElementById("mf-pager-style")) return; const st = document.createElement("style"); st.id = "mf-pager-style"; st.textContent = ".mf-pager{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:12px 0;padding:10px;border:1px solid #e5e7eb;border-radius:12px;background:#fafafa;font-size:12px;color:#4b5563}.mf-pager-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.mf-pager button,.mf-pager select{border:1px solid #d1d5db;border-radius:999px;background:#fff;padding:6px 10px;font-size:12px;cursor:pointer}.mf-pager button:disabled{opacity:.35;cursor:not-allowed}.mf-pager select{border-radius:8px}.mf-hidden{display:none!important}@media(max-width:640px){.mf-pager{align-items:flex-start;flex-direction:column}}"; document.head.appendChild(st); }
  function pager() { let p = $("mfPager"); if (p || !E.results) return p; stylePager(); p = document.createElement("div"); p.id = "mfPager"; p.className = "mf-pager"; p.innerHTML = `<div id="mfInfo"></div><div class="mf-pager-actions"><button id="mfPrev" type="button">‹</button><button id="mfNext" type="button">›</button><label>${t("表示", "Show")} <select id="mfPer"><option value="24">24</option><option value="48" selected>48</option><option value="96">96</option></select></label></div>`; E.results.after(p); $("mfPrev").onclick = () => { S.page = Math.max(1, S.page - 1); render(); }; $("mfNext").onclick = () => { S.page += 1; render(); }; $("mfPer").onchange = (e) => { S.per = Number(e.target.value) || 48; S.page = 1; render(); }; return p; }
  function filter(keywordOverride) { const q = norm(keywordOverride || (E.q ? E.q.value : "")); const cat = E.cat ? E.cat.value : ""; let list = S.all.slice(); if (q) list = list.filter((x) => searchText(x).includes(q)); if (cat) list = list.filter((x) => x.category === cat); S.filtered = list; S.page = 1; render(); }
  function txt(tag, cls, v) { const n = document.createElement(tag); n.className = cls; n.textContent = v; return n; }
  function render() { if (!E.results || !E.count) return; const p = pager(); const list = S.filtered || []; E.results.innerHTML = ""; if (!S.all.length) { E.count.textContent = t("読み込み中...", "Loading..."); if (p) p.classList.add("mf-hidden"); return; } if (!list.length) { E.count.textContent = t("0件", "0 records"); if (p) p.classList.add("mf-hidden"); if (E.emptyJa) E.emptyJa.hidden = S.lang !== "ja"; if (E.emptyEn) E.emptyEn.hidden = S.lang !== "en"; return; } if (E.emptyJa) E.emptyJa.hidden = true; if (E.emptyEn) E.emptyEn.hidden = true; const pages = Math.max(1, Math.ceil(list.length / S.per)); S.page = Math.min(Math.max(1, S.page), pages); const start = (S.page - 1) * S.per; const items = list.slice(start, start + S.per); const end = start + items.length; E.count.textContent = t(`全${list.length}件中 ${start + 1}-${end}件`, `Showing ${start + 1}-${end} of ${list.length}`); p.classList.remove("mf-hidden"); $("mfInfo").textContent = t(`${S.page}/${pages}ページ`, `Page ${S.page}/${pages}`); $("mfPrev").disabled = S.page <= 1; $("mfNext").disabled = S.page >= pages; $("mfPer").value = String(S.per); const frag = document.createDocumentFragment(); items.forEach((x) => { const card = document.createElement("article"); card.className = "card"; card.appendChild(txt("div", "card-title", S.lang === "ja" ? x.nameJa : x.nameEn)); const meta = document.createElement("div"); meta.className = "card-meta"; meta.appendChild(txt("span", "card-category", x.category)); if (x.country) meta.appendChild(txt("span", "card-country", x.country)); card.appendChild(meta); card.appendChild(txt("p", "card-note", x.note)); card.appendChild(txt("p", "card-hint", t(`検索ヒント：${x.hint}`, `Search hint: ${x.hint}`))); if (x.linkReview) card.appendChild(txt("p", "card-audit", t("確認：公式入口として整理済み", "Checked: official entry normalized"))); const links = document.createElement("div"); links.className = "card-links"; if (x.manualUrl) { const a = document.createElement("a"); a.href = x.manualUrl; a.target = "_blank"; a.rel = "noopener noreferrer"; a.textContent = t("公式マニュアル", "Official manuals"); links.appendChild(a); } if (x.supportUrl) { const a = document.createElement("a"); a.href = x.supportUrl; a.target = "_blank"; a.rel = "noopener noreferrer"; a.textContent = t("サポートTOP", "Support portal"); links.appendChild(a); } links.appendChild(txt("span", "tag-official", t("公式サイト", "Official"))); card.appendChild(links); frag.appendChild(card); }); E.results.appendChild(frag); }
  async function initData() { if (E.status) E.status.textContent = t("データを読み込み中です...", "Loading manual directory..."); try { await loadScript(FULL); if (!Array.isArray(window.MANUALFINDER_FULL_RECORDS)) throw new Error("full missing"); S.all = normalize(window.MANUALFINDER_FULL_RECORDS); } catch (e) { try { const r = await fetch(JSON_URL, { cache: "no-store" }); S.all = normalize(await r.json()); } catch (_) { S.all = []; } } if (E.status) E.status.hidden = true; filter(); }
  function bind() { E.langBtns.forEach((b) => b.onclick = () => { const v = b.getAttribute("data-lang"); if (v) lang(v); }); if (E.q) E.q.oninput = () => filter(); if (E.cat) E.cat.onchange = () => filter(); if (E.quick) E.quick.onclick = (ev) => { const b = ev.target.closest("button"); if (!b) return; const c = b.getAttribute("data-category"); const k = b.getAttribute("data-keyword") || b.getAttribute("data-brand") || ""; if (c) { if (E.cat) E.cat.value = c; if (E.q) E.q.value = ""; filter(); } else if (k) { if (E.q) E.q.value = k; if (E.cat) E.cat.value = ""; filter(k); } }; }
  document.addEventListener("DOMContentLoaded", () => { lang(S.lang); bind(); initData(); });
})();
