(() => {
  const C={pc:'PC・スマホ',home:'家電',printer:'プリンター・複合機',camera:'カメラ・映像',audio:'オーディオ',game:'ゲーム',net:'ネットワーク機器',other:'その他'};
  const isEn=/\/manual-finder\/en\/?/.test(location.pathname); const S={all:[],filtered:[],page:1,per:48,lang:isEn?'en':'ja'};
  const $=id=>document.getElementById(id); const E={r:$('results'),c:$('resultCount'),st:$('loadStatus'),q:$('searchInput'),cat:$('categorySelect'),quick:$('quickButtons'),ej:$('emptyMessage'),ee:$('emptyMessageEn'),i18n:document.querySelectorAll('[data-i18n]'),lbs:document.querySelectorAll('.nw-lang-switch button')};
  const makers=[
    ['Apple','Apple','Global','https://support.apple.com/','iPhone:pc,iPad:pc,MacBook:pc,iMac:pc,Mac mini:pc,Apple Watch:other,AirPods:audio,HomePod:audio,Apple TV:home,Studio Display:pc'],
    ['Sony','ソニー','Japan','https://www.sony.jp/support/','BRAVIA:home,BD Recorder:home,Xperia:pc,Alpha Camera:camera,Cyber-shot:camera,Handycam:camera,Walkman:audio,WH Headphones:audio,WF Earbuds:audio,SRS Speaker:audio,HT Soundbar:audio,PlayStation:game'],
    ['Panasonic','パナソニック','Japan','https://panasonic.jp/support/','VIERA:home,DIGA:home,LUMIX:camera,Let’s note:pc,Washing Machine:home,Refrigerator:home,Microwave Oven:home,Rice Cooker:home,Air Conditioner:home,Hair Dryer:home,Intercom:other,Battery:other'],
    ['Sharp','シャープ','Japan','https://jp.sharp/support/','AQUOS TV:home,AQUOS Phone:pc,Plasmacluster Air Purifier:home,Refrigerator:home,Washing Machine:home,Microwave Oven:home,Air Conditioner:home,Vacuum Cleaner:home,Calculator:other,Electronic Dictionary:other'],
    ['Hitachi','日立','Japan','https://kadenfan.hitachi.co.jp/support/','Washing Machine:home,Refrigerator:home,Vacuum Cleaner:home,Air Conditioner:home,Microwave Oven:home,Rice Cooker:home,IH Cooker:home,Dryer:home,Air Purifier:home,Lighting:home'],
    ['Toshiba','東芝','Japan','https://www.toshiba-lifestyle.com/jp/support/','REGZA TV:home,REGZA Recorder:home,Washing Machine:home,Refrigerator:home,Vacuum Cleaner:home,Microwave Oven:home,Rice Cooker:home,Air Conditioner:home,Lighting:home,Battery:other'],
    ['Mitsubishi Electric','三菱電機','Japan','https://www.mitsubishielectric.co.jp/support/','Air Conditioner:home,Refrigerator:home,IH Cooker:home,Rice Cooker:home,Vacuum Cleaner:home,LCD Display:pc,Projector:camera,Ventilation Fan:home,EcoCute:home,Dehumidifier:home'],
    ['Daikin','ダイキン','Japan','https://www.daikin.co.jp/support/','Air Conditioner:home,Air Purifier:home,Humidifier:home,Remote Controller:home,Ventilation:home,EcoCute:home,Commercial AC:home,App:other'],
    ['Iris Ohyama','アイリスオーヤマ','Japan','https://www.irisohyama.co.jp/support/','Rice Cooker:home,Vacuum Cleaner:home,Air Conditioner:home,TV:home,Refrigerator:home,Washing Machine:home,Lighting:home,Pet Appliance:home'],
    ['Yamazen','山善','Japan','https://book.yamazen.co.jp/','Fan:home,Heater:home,Microwave Oven:home,Kitchen Appliance:home,Vacuum Cleaner:home,Air Circulator:home,Electric Blanket:home,Furniture Appliance:home'],
    ['Balmuda','バルミューダ','Japan','https://www.balmuda.com/jp/support/','The Toaster:home,The Range:home,The Pot:home,GreenFan:home,AirEngine:home,Lantern:home'],
    ['Zojirushi','象印マホービン','Japan','https://www.zojirushi.co.jp/toiawase/','Rice Cooker:home,Electric Pot:home,Water Bottle:other,Hot Plate:home,Coffee Maker:home,Air Pot:home'],
    ['Tiger','タイガー魔法瓶','Japan','https://www.tiger-corporation.com/ja/jpn/support/','Rice Cooker:home,Electric Pot:home,Bottle:other,Coffee Maker:home,Hot Plate:home,Blender:home'],
    ['Canon','キヤノン','Japan','https://canon.jp/support','EOS Camera:camera,PowerShot:camera,RF Lens:camera,EF Lens:camera,PIXUS:printer,imageRUNNER:printer,CanoScan:printer,SELPHY:printer,Projector:camera,Calculator:other'],
    ['Nikon','ニコン','Japan','https://downloadcenter.nikonimglib.com/','Z Camera:camera,D Camera:camera,COOLPIX:camera,NIKKOR Lens:camera,Speedlight:camera,Binoculars:other,NX Studio:camera,Battery Charger:camera'],
    ['Fujifilm','富士フイルム','Japan','https://www.fujifilm.com/jp/ja/consumer/support','X Camera:camera,GFX:camera,XF Lens:camera,GF Lens:camera,instax:camera,instax Printer:printer,Apeos:printer,DocuPrint:printer,Scanner:printer'],
    ['OM System','OM System / Olympus','Global','https://support.jp.omsystem.com/','OM Camera:camera,PEN Camera:camera,M.ZUIKO Lens:camera,Voice Recorder:audio,Binoculars:other,Flash:camera'],
    ['Ricoh','リコー','Japan','https://www.ricoh.co.jp/support','GR Camera:camera,THETA:camera,PENTAX Camera:camera,Printer:printer,Scanner:printer,Projector:camera'],
    ['DJI','DJI','Global','https://www.dji.com/support','Mavic:camera,Mini Drone:camera,Air Drone:camera,Avata:camera,Osmo:camera,Action Camera:camera,Ronin:camera,DJI Mic:audio,Goggles:camera,Power Station:other'],
    ['GoPro','GoPro','Global','https://gopro.com/en/us/support','HERO:camera,MAX:camera,Media Mod:camera,Remote:camera,Battery:other,Mount:other'],
    ['Insta360','Insta360','Global','https://www.insta360.com/support','X Series:camera,GO Series:camera,ONE RS:camera,Ace Pro:camera,Flow Gimbal:camera,Mic:audio'],
    ['Epson','エプソン','Japan','https://www.epson.jp/support/','Inkjet Printer:printer,Business Printer:printer,Scanner:printer,Projector:camera,Label Printer:printer,Large Format Printer:printer,Receipt Printer:printer,MOVERIO:other'],
    ['Brother','ブラザー','Japan','https://support.brother.co.jp/','Inkjet Printer:printer,Laser Printer:printer,Label Writer:printer,Sewing Machine:other,Scanner:printer,Fax:printer,ScanNCut:other,Embroidery Machine:other'],
    ['HP','日本HP','Global','https://support.hp.com/','Laptop:pc,Desktop:pc,Printer:printer,Monitor:pc,Workstation:pc,Dock:pc,Scanner:printer,Gaming PC:game'],
    ['Dell','デル','Global','https://www.dell.com/support/home/','XPS:pc,Inspiron:pc,Latitude:pc,Precision:pc,Alienware:game,Monitor:pc,PowerEdge:pc,Dock:pc'],
    ['Lenovo','レノボ','Global','https://support.lenovo.com/','ThinkPad:pc,IdeaPad:pc,Yoga:pc,Legion:game,Tablet:pc,ThinkVision:pc,Dock:pc,Workstation:pc'],
    ['ASUS','ASUS','Global','https://www.asus.com/support/','Zenbook:pc,Vivobook:pc,ROG Laptop:game,ROG Ally:game,Router:net,Monitor:pc,Motherboard:other,Zenfone:pc'],
    ['Acer','Acer','Global','https://www.acer.com/support','Aspire:pc,Swift:pc,Predator:game,Nitro:game,Monitor:pc,Projector:camera,Chromebook:pc,Desktop:pc'],
    ['MSI','MSI','Global','https://www.msi.com/support','Laptop:pc,Motherboard:other,Graphics Card:other,Monitor:pc,Desktop:pc,Gaming Handheld:game,Keyboard:game,Mouse:game'],
    ['LG','LG','Global','https://www.lg.com/support','TV:home,Monitor:pc,Washing Machine:home,Refrigerator:home,Soundbar:audio,Air Conditioner:home,Projector:camera,Styler:home'],
    ['Samsung','Samsung','Global','https://www.samsung.com/support/','Galaxy Phone:pc,Galaxy Tab:pc,Galaxy Watch:other,TV:home,Monitor:pc,SSD:other,Soundbar:audio,Buds:audio'],
    ['Google','Google','Global','https://support.google.com/','Pixel:pc,Pixel Buds:audio,Pixel Watch:other,Nest Hub:other,Nest Cam:camera,Chromecast:home,Nest Wifi:net,Fitbit:other'],
    ['Microsoft','Microsoft','Global','https://support.microsoft.com/','Surface Pro:pc,Surface Laptop:pc,Surface Go:pc,Xbox Console:game,Xbox Controller:game,Keyboard:pc,Mouse:pc,HoloLens:other'],
    ['Nintendo','任天堂','Japan','https://www.nintendo.co.jp/support/','Switch:game,Switch Lite:game,Switch OLED:game,Joy-Con:game,Pro Controller:game,3DS:game,Wii U:game,Amiibo:game'],
    ['PlayStation','PlayStation','Global','https://www.playstation.com/support/','PS5 Console:game,PS4 Console:game,DualSense:game,PS VR2:game,Portal:game,Pulse Headset:audio'],
    ['Valve','Valve','Global','https://help.steampowered.com/','Steam Deck:game,Steam Controller:game,Steam Link:game,Dock:game'],
    ['Meta','Meta','Global','https://www.meta.com/help/quest/','Quest 2:game,Quest 3:game,Quest Pro:game,Touch Controller:game,Charging Dock:game'],
    ['Yamaha','ヤマハ','Japan','https://jp.yamaha.com/support/','AV Receiver:audio,Soundbar:audio,Speaker:audio,Piano:other,Keyboard:other,Mixer:audio,Router:net,Guitar Amp:audio'],
    ['Bose','Bose','Global','https://support.bose.com/','QuietComfort:audio,SoundLink:audio,Soundbar:audio,Earbuds:audio,Home Speaker:audio,Amplifier:audio'],
    ['JBL','JBL','Global','https://support.jbl.com/','Headphones:audio,Earbuds:audio,Speaker:audio,Soundbar:audio,PartyBox:audio,Quantum:game'],
    ['Sennheiser','Sennheiser','Global','https://www.sennheiser-hearing.com/support/','MOMENTUM:audio,HD Headphones:audio,Earbuds:audio,AMBEO:audio,Microphone:audio,Wireless:audio'],
    ['Audio-Technica','オーディオテクニカ','Japan','https://www.audio-technica.co.jp/support/','Headphones:audio,Microphone:audio,Turntable:audio,Cartridge:audio,Wireless:audio,Gaming:game'],
    ['Denon','デノン','Global','https://support.denon.com/','AV Receiver:audio,Soundbar:audio,Speaker:audio,CD Player:audio,Turntable:audio,Headphones:audio'],
    ['Marantz','マランツ','Global','https://support.marantz.com/','Amplifier:audio,AV Receiver:audio,CD Player:audio,Network Audio:audio,Turntable:audio,Speaker:audio'],
    ['TP-Link','TP-Link','Global','https://www.tp-link.com/support/','Archer Router:net,Deco Mesh:net,Tapo Camera:camera,Tapo Smart Plug:other,Switch:net,Adapter:net,Omada:net,Repeater:net'],
    ['Buffalo','バッファロー','Japan','https://www.buffalo.jp/support/','AirStation:net,LinkStation:net,TeraStation:net,HDD:other,SSD:other,Keyboard:pc,Mouse:pc,Hub:net'],
    ['Synology','Synology','Global','https://www.synology.com/support','DiskStation:net,Router:net,Expansion Unit:net,Camera:camera,DSM:net,Switch:net'],
    ['QNAP','QNAP','Global','https://www.qnap.com/en/support','TS NAS:net,TVS NAS:net,Switch:net,Router:net,Expansion Unit:net,QTS:net'],
    ['Ubiquiti','Ubiquiti','Global','https://help.ui.com/','UniFi Gateway:net,UniFi AP:net,UniFi Switch:net,UniFi Camera:camera,Dream Machine:net,Cloud Key:net'],
    ['Garmin','Garmin','Global','https://support.garmin.com/','Forerunner:other,fenix:other,Venu:other,Edge:other,Dash Cam:camera,Marine:other,GPS:other,Scale:other'],
    ['Fitbit','Fitbit','Global','https://help.fitbit.com/','Charge:other,Versa:other,Sense:other,Inspire:other,Ace:other'],
    ['Anker','Anker','Global','https://support.anker.com/','Charger:other,Power Bank:other,USB Hub:pc,Soundcore:audio,Eufy:other,Nebula Projector:camera,Work Webcam:camera,Dock:pc'],
    ['Eufy','Eufy','Global','https://support.eufy.com/','RoboVac:home,Security Camera:camera,Video Doorbell:camera,Smart Lock:other,Baby Monitor:camera'],
    ['Ring','Ring','Global','https://ring.com/support','Video Doorbell:camera,Stick Up Cam:camera,Floodlight Cam:camera,Alarm:other,Chime:other'],
    ['Amazon Devices','Amazon Devices','Global','https://www.amazon.com/gp/help/customer/display.html','Kindle:other,Echo:audio,Fire TV:home,Fire Tablet:pc,Eero:net,Blink Camera:camera'],
    ['Makita','マキタ','Japan','https://www.makita.co.jp/product/support/','Impact Driver:other,Drill:other,Circular Saw:other,Vacuum Cleaner:home,Battery Charger:other,Radio:audio,Grass Trimmer:other,Blower:other'],
    ['HiKOKI','HiKOKI','Japan','https://www.hikoki-powertools.jp/manual/','Impact Driver:other,Drill:other,Grinder:other,Circular Saw:other,Battery Charger:other,Dust Collector:home,Nailer:other,Blower:other'],
    ['Bosch Tools','ボッシュ工具','Global','https://www.boschtools.com/us/en/service/product-manuals/','Drill:other,Driver:other,Measuring Tool:other,Sander:other,Saw:other,Laser Measure:other'],
    ['Karcher','ケルヒャー','Global','https://www.kaercher.com/int/services/support/manuals.html','Pressure Washer:home,Steam Cleaner:home,Vacuum:home,Window Cleaner:home,Floor Cleaner:home,Accessory:other'],
    ['Dyson','ダイソン','Global','https://www.dyson.com/support','Vacuum Cleaner:home,Air Purifier:home,Hair Dryer:home,Airwrap:home,Fan:home,Light:home'],
    ['iRobot','iRobot','Global','https://homesupport.irobot.com/','Roomba:home,Braava:home,Combo:home,Dock:home,Battery:other,App:other'],
    ['Roborock','Roborock','Global','https://support.roborock.com/','Robot Vacuum:home,Dock:home,Wet Dry Vacuum:home,App:other,Accessory:other'],
    ['Omron Healthcare','オムロンヘルスケア','Japan','https://www.healthcare.omron.co.jp/support/','Blood Pressure Monitor:other,Thermometer:other,Nebulizer:other,Scale:other,Activity Meter:other,Low Frequency Therapy:other'],
    ['Tanita','タニタ','Japan','https://www.tanita.co.jp/support/','Scale:other,Body Composition Monitor:other,Thermometer:other,Timer:other,Pedometer:other,Kitchen Scale:home'],
    ['Toyota','トヨタ','Japan','https://manual.toyota.jp/','Aqua:other,Prius:other,Corolla:other,Yaris:other,Sienta:other,Navigation:other'],
    ['Honda','ホンダ','Japan','https://www.honda.co.jp/ownersmanual/','N-BOX:other,Fit:other,Civic:other,Vezel:other,Freed:other,Navigation:other'],
    ['Nissan','日産','Japan','https://www.nissan.co.jp/OPTIONAL-PARTS/NAVIOM/','Note:other,Serena:other,Leaf:other,Sakura:other,X-Trail:other,Navigation:other'],
    ['Mazda','マツダ','Japan','https://www.mazda.co.jp/carlife/owner/manual/','Mazda2:other,Mazda3:other,CX-5:other,CX-30:other,Roadster:other,Navigation:other'],
    ['Subaru','スバル','Japan','https://www.subaru.jp/afterservice/tnst/','Impreza:other,Forester:other,Outback:other,Levorg:other,Crosstrek:other,Navigation:other'],
    ['Kenwood','JVCケンウッド','Japan','https://www.kenwood.com/jp/cs/','Car Navigation:other,Dash Cam:camera,Car Audio:audio,Receiver:audio,Speaker:audio,Transceiver:other'],
    ['Pioneer','パイオニア','Japan','https://jpn.pioneer/ja/support/manual/','Car Navigation:other,Dash Cam:camera,Car Audio:audio,Speaker:audio,Subwoofer:audio,ETC:other'],
    ['Eizo','EIZO','Japan','https://www.eizo.co.jp/support/db/','FlexScan:pc,ColorEdge:pc,FORIS:game,RadiForce:pc,DuraVision:pc'],
    ['BenQ','BenQ','Global','https://www.benq.com/en-us/support/downloads-faq.html','Monitor:pc,Projector:camera,Gaming Monitor:game,ScreenBar:home,Speaker:audio'],
    ['Wacom','ワコム','Global','https://www.wacom.com/support/product-support/manuals','Intuos:other,Cintiq:other,One:other,MobileStudio:pc,Pen:other,Tablet Driver:pc']
  ];
  const notes={}; Object.values(C).forEach(c=>notes[c]=`${c} の公式マニュアル／サポート入口です。`);
  const records=[]; makers.forEach(([brand,nameJa,country,url,lineText])=>{lineText.split(',').forEach(spec=>{const [line,key]=spec.split(':'); const category=C[key]||C.other; records.push({brand:`${brand} ${line}`,nameJa:`${nameJa} ${line}`,nameEn:`${brand} ${line}`,category,country,manualUrl:url,supportUrl:url,note:notes[category],hint:`${line} 型番、製品名、シリーズ名`,tags:`${brand} ${nameJa} ${line} ${category}`.toLowerCase().split(/\s+/),sourceType:'official',linkReview:'curated maker-line entry 2026-05-13'});});});
  const seen=new Set(); window.MANUALFINDER_CURATED_RECORDS=records.filter(x=>{const k=`${x.brand}|${x.category}`.toLowerCase(); if(seen.has(k)) return false; seen.add(k); return true;});
})();
