let MUNICIPALITIES=[];
let currentLang="ja";
const PREF_ORDER=["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"];
const TEXT={ja:{searchButton:"検索する",resetButton:"条件クリア",placeholder:"例：分別、カレンダー、粗大ごみ",allOption:"すべて / All",found:n=>`該当自治体：${n}件`,noResult:"該当する自治体が見つかりませんでした。都道府県のみ、またはキーワードなしで再検索してください。",loadError:"データの読み込みに失敗しました。時間をおいて再度お試しください。",conditionAll:"現在の条件：すべて",condition:v=>{const p=[];if(v.pref)p.push(`都道府県：${v.pref}`);if(v.city)p.push(`市区町村：${v.city}`);if(v.keyword)p.push(`キーワード：${v.keyword}`);return p.length?`現在の条件：${p.join(" / ")}`:"現在の条件：すべて"},openOfficial:"公式ページを開く",site:"外部サイト",note:"自治体トップページまたは行政区ページです。ごみ分別・収集カレンダー・粗大ごみ情報はリンク先サイト内で確認してください。",url:"URL",emptyTitle:"見つかりませんでした",emptyHint:"都道府県だけを選ぶ、またはキーワードを空にして再検索してください。"},en:{searchButton:"Search",resetButton:"Reset",placeholder:"e.g. sorting, calendar, bulky waste",allOption:"All",found:n=>`${n} results`,noResult:"No matching municipality found. Try selecting only a prefecture or removing the keyword.",loadError:"Failed to load data. Please try again later.",conditionAll:"Current filters: All",condition:v=>{const p=[];if(v.pref)p.push(`Prefecture: ${v.pref}`);if(v.city)p.push(`Municipality: ${v.city}`);if(v.keyword)p.push(`Keyword: ${v.keyword}`);return p.length?`Current filters: ${p.join(" / ")}`:"Current filters: All"},openOfficial:"Open official page",site:"External site",note:"This is a municipal or ward official page. Confirm waste sorting, pickup calendars, and bulky waste information on the linked site.",url:"URL",emptyTitle:"No results found",emptyHint:"Try selecting only a prefecture or clearing the keyword."}};

document.addEventListener("DOMContentLoaded",()=>{
  const el={pref:$("prefSelect"),city:$("citySelect"),kw:$("keywordInput"),search:$("searchButton"),reset:$("resetButton"),results:$("results"),summary:$("resultSummary"),cond:$("currentConditions"),count:$("municipalityCount"),countEn:$("municipalityCountEn")};
  initI18n(el);
  loadMunicipalities().then(data=>{MUNICIPALITIES=normalizeMunicipalities(data);initPrefOptions(el.pref,MUNICIPALITIES);if(el.count)el.count.textContent=`${MUNICIPALITIES.length}件`;if(el.countEn)el.countEn.textContent=String(MUNICIPALITIES.length);updateConditions(el);renderResults(MUNICIPALITIES,el.results,el.summary);}).catch(e=>{console.error(e);el.summary.textContent=TEXT[currentLang].loadError;el.results.innerHTML="";});
  el.pref.addEventListener("change",()=>{updateCityOptions(el.pref,el.city,MUNICIPALITIES);runSearch(el);});
  el.city.addEventListener("change",()=>runSearch(el));
  el.search.addEventListener("click",()=>runSearch(el));
  el.kw.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();el.search.click();}});
  el.reset.addEventListener("click",()=>{el.pref.value="";el.city.innerHTML=`<option value="">${TEXT[currentLang].allOption}</option>`;el.city.disabled=true;el.kw.value="";updateConditions(el);renderResults(MUNICIPALITIES,el.results,el.summary);});
  document.querySelectorAll(".quick-pref").forEach(b=>b.addEventListener("click",()=>{el.pref.value=b.dataset.pref||"";updateCityOptions(el.pref,el.city,MUNICIPALITIES);el.city.value="";runSearch(el);}));
});
function $(id){return document.getElementById(id)}
function fetchJson(path,required=false){return fetch(path,{cache:"no-store"}).then(r=>{if(!r.ok){if(required)throw new Error(`${path}: HTTP ${r.status}`);return []}return r.json()}).then(d=>Array.isArray(d)?d:[]).catch(e=>{if(required)throw e;console.warn(e);return []})}
function loadMunicipalities(){return Promise.all([fetchJson("data/localgovjp-lite.json",false),fetchJson("data/municipalities.json",true),fetchJson("data/municipalities-extra.json",false)]).then(([national,base,extra])=>national.length?national.concat(base,extra):base.concat(extra))}
function normalizeMunicipalities(data){const seen=new Set(),rank=new Map(PREF_ORDER.map((p,i)=>[p,i]));return data.map(x=>{const pref=String(x.pref||"").trim(),city=String(x.city||"").trim(),url=String(x.url||"").trim();return{pref,city,name:x.name||`${city} 公式サイト`,type:x.type||"自治体公式ページ",url,lgcode:x.lgcode||""}}).filter(x=>x.pref&&x.city&&/^https?:\/\//.test(x.url)).filter(x=>{const k=x.lgcode?`lgcode:${x.lgcode}`:`${x.pref}:${x.city}:${x.url}`;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const d=(rank.get(a.pref)??999)-(rank.get(b.pref)??999);return d||String(a.city).localeCompare(String(b.city),"ja")})}
function initI18n(el){const btns=document.querySelectorAll(".nw-lang-switch button"),nodes=document.querySelectorAll("[data-i18n]"),keyed=document.querySelectorAll("[data-i18n-key]");currentLang=(navigator.language||"").toLowerCase().startsWith("ja")?"ja":"en";const apply=lang=>{currentLang=lang;document.documentElement.lang=lang;nodes.forEach(n=>{n.style.display=n.dataset.i18n===lang?"":"none"});keyed.forEach(n=>{const k=n.dataset.i18nKey;if(TEXT[lang][k])n.textContent=TEXT[lang][k]});btns.forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));if(el.kw)el.kw.placeholder=TEXT[lang].placeholder;if(el.cond)el.cond.textContent=TEXT[lang].conditionAll;if(MUNICIPALITIES.length){updateSelectPlaceholders(el.pref,el.city);runSearch(el)}};btns.forEach(b=>b.addEventListener("click",()=>apply(b.dataset.lang)));apply(currentLang)}
function updateSelectPlaceholders(pref,city){if(pref&&pref.options.length)pref.options[0].textContent=TEXT[currentLang].allOption;if(city&&city.options.length)city.options[0].textContent=TEXT[currentLang].allOption}
function initPrefOptions(select,data){select.innerHTML=`<option value="">${TEXT[currentLang].allOption}</option>`;[...new Set(data.map(x=>x.pref).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja")).forEach(pref=>{const o=document.createElement("option");o.value=pref;o.textContent=pref;select.appendChild(o)})}
function updateCityOptions(prefSelect,citySelect,data){const pref=prefSelect.value,cities=[...new Set(data.filter(x=>!pref||x.pref===pref).map(x=>x.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"));citySelect.innerHTML=`<option value="">${TEXT[currentLang].allOption}</option>`;citySelect.disabled=!cities.length;cities.forEach(city=>{const o=document.createElement("option");o.value=city;o.textContent=city;citySelect.appendChild(o)})}
function runSearch(el){const list=filterMunicipalities({pref:el.pref.value,city:el.city.value,keyword:el.kw.value});updateConditions(el);renderResults(list,el.results,el.summary)}
function updateConditions(el){if(!el.cond)return;el.cond.textContent=TEXT[currentLang].condition({pref:el.pref.value,city:el.city.value,keyword:el.kw.value.trim()})}
function filterMunicipalities({pref,city,keyword}){const kw=(keyword||"").trim().toLowerCase();return MUNICIPALITIES.filter(x=>{if(pref&&x.pref!==pref)return false;if(city&&x.city!==city)return false;if(!kw)return true;return[x.pref,x.city,x.name,x.type,x.url,x.lgcode].join(" ").toLowerCase().includes(kw)})}
function typeLabel(type,lang){return lang==="ja"?"自治体公式ページ":"Official municipal page"}
function renderResults(list,container,summary){container.innerHTML="";if(!Array.isArray(list)||!list.length){summary.textContent=TEXT[currentLang].noResult;const e=document.createElement("div");e.className="empty-state";const t=document.createElement("p");t.className="empty-title";t.textContent=TEXT[currentLang].emptyTitle;const h=document.createElement("p");h.className="empty-hint";h.textContent=TEXT[currentLang].emptyHint;e.append(t,h);container.appendChild(e);return}summary.textContent=TEXT[currentLang].found(list.length);list.forEach(x=>{const c=document.createElement("div");c.className="result-card";const title=document.createElement("p");title.className="result-title";title.textContent=`${x.pref} ${x.city}`;const meta=document.createElement("p");meta.className="result-meta";meta.textContent=x.name;const tag=document.createElement("span");tag.className="result-tag";tag.textContent=typeLabel(x.type,currentLang);const note=document.createElement("p");note.className="result-note";note.textContent=TEXT[currentLang].note;const a=document.createElement("a");a.className="result-button";a.href=x.url;a.target="_blank";a.rel="noopener noreferrer";a.textContent=TEXT[currentLang].openOfficial;const ext=document.createElement("span");ext.className="external-label";ext.textContent=TEXT[currentLang].site;a.appendChild(ext);const url=document.createElement("p");url.className="result-url";url.textContent=`${TEXT[currentLang].url}: ${x.url}`;c.append(title,meta,tag,note,a,url);container.appendChild(c)})}
