const state = { lang: 'ja', dict: {}, meta: {}, compatibility: {}, last: null };

const i18n = {
  ja: { title:'古文書旧字体ハイライター', desc:'古い文章・碑文・古地図説明・旧公文書風テキストに含まれる旧字体・異体字をハイライトし、現代表記との対応を確認するための参考ツールです。翻訳・解読・学術的判定を行うものではありません。', inputLabel:'文章を貼り付け', analyze:'ハイライトする', detection:'検出結果', found:'本文中に登録済みの旧字体・異体字が見つかりました。', none:'本文中に登録済みの旧字体・異体字は見つかりませんでした。', matches:'検出数', unique:'種類', highlightTitle:'ハイライト表示', modernTitle:'現代表記プレビュー', modernNote:'これは機械的な置換プレビューです。文意・固有名詞・正式表記を保証するものではありません。', copyOld:'旧字だけコピー', copyPairs:'対応表をコピー', copyModern:'現代表記プレビューをコピー', copied:'コピーしました', cautionHead:'古い文章を読む場合の注意', cautionBody:'このツールは旧字体・異体字の検出と対応確認を補助する参考ツールです。文意の解釈、翻刻、翻訳、学術的判定、法的判断を行うものではありません。固有名詞・地名・人名・正式表記は、必ず原資料や信頼できる資料で確認してください。', privacy:'入力内容はブラウザ内で処理され、外部APIには送信しません。アクセス解析や広告タグが読み込まれる場合があります。', viewRef:'旧字体一覧で詳しく見る', toConverter:'文章全体を旧字体変換ツールで確認する', old:'旧字', modern:'新字', occurrences:'出現', reading:'読み', meaning:'意味', category:'分類', usage:'用途', rendering:'表示環境の注意', copyOldCard:'旧字をコピー', copyModernCard:'新字をコピー', proFeatureTitle:'一括処理・レポート・出力・保存セット・監査メモは Pro 機能です', proFeatureText:'検出リスト、現代表記プレビュー、コピー操作の一括処理、レポート作成、出力、保存セット、監査メモは Old Kanji Toolkit Pro で利用できます。', proCta:'Pro を確認する', proPanelBillingNote:'現在、Pro機能は準備中です。課金導線はまだ接続されていません。' },
  en: { title:'Old Document Kanji Highlighter', desc:'A reference tool for highlighting old or variant kanji forms in old-style documents, inscriptions, old map descriptions, and historical-looking text. It does not provide translation, scholarly interpretation, or official judgment.', inputLabel:'Paste text', analyze:'Highlight old kanji', detection:'Detection result', found:'Registered old or variant kanji forms were found in the text.', none:'No registered old or variant kanji forms were found in the text.', matches:'Matches', unique:'Unique forms', highlightTitle:'Highlighted text', modernTitle:'Modern-form preview', modernNote:'This is a mechanical replacement preview. It does not guarantee meaning, proper nouns, or official spelling.', copyOld:'Copy old forms only', copyPairs:'Copy pair table', copyModern:'Copy modern preview', copied:'Copied', cautionHead:'Important note for old documents', cautionBody:'This tool is a reference aid for detecting old or variant kanji forms and checking their modern mappings. It does not provide interpretation, transcription, translation, scholarly judgment, or legal judgment. Proper nouns, place names, personal names, and official spellings should be confirmed against the original or reliable sources.', privacy:'Input is processed in the browser and is not sent to an external API. Analytics or ad tags may be loaded on the page.', viewRef:'View in Old Kanji Reference', toConverter:'Check full text in converter', old:'Old', modern:'Modern', occurrences:'Occurrences', reading:'Reading', meaning:'Meaning', category:'Category', usage:'Usage', rendering:'Rendering note', copyOldCard:'Copy old', copyModernCard:'Copy modern', proFeatureTitle:'Batch, reports, exports, saved sets, and audit notes are Pro features', proFeatureText:'Batch processing, report generation, exports, saved sets, and audit notes for detected lists, modern previews, and copy workflows are available in Old Kanji Toolkit Pro.', proCta:'View Pro', proPanelBillingNote:'Pro features are being prepared. Billing is not connected yet.' }
};

async function loadData() { const d = await fetch('../old-kanji-reference/dict.json').then(r => r.json()); state.dict = buildReverseLookupFromOldToNew(d.old_to_new || {}); }
function buildReverseLookupFromOldToNew(oldToNew){ return oldToNew; }
async function loadMetadata(){ const files=['meta.json','meta-extra-2.json','meta-extra-3.json','meta-extra-4.json','meta-extra-5.json','meta-extra-6.json']; let entries={}; for(const f of files){ try{ const j=await fetch(`../old-kanji-reference/${f}`).then(r=>r.json()); if(j.entries) entries={...entries,...j.entries}; }catch{} } state.meta=entries; }
async function loadCompatibilityNotes(){ try{ const j=await fetch('../old-kanji-reference/compatibility-notes.json').then(r=>r.json()); state.compatibility=j.entries||{}; } catch { state.compatibility={}; } }
function getFallbackCompatibilityNote(ch){ const cp=ch.codePointAt(0); if(cp>=0xF900&&cp<=0xFAFF) return {summaryJa:'CJK互換漢字のため表示差に注意してください。',summaryEn:'CJK compatibility ideograph; rendering may vary.'}; if(cp>0xFFFF) return {summaryJa:'補助平面文字のため環境依存の可能性があります。',summaryEn:'Supplementary-plane character; environment-dependent rendering is possible.'}; if((cp>=0xFE00&&cp<=0xFE0F)||(cp>=0xE0100&&cp<=0xE01EF)) return {summaryJa:'異体字セレクタを含む可能性があります。',summaryEn:'May include variation selectors.'}; return null; }
function countMatches(text){ const counts={}; for(const ch of text){ if(state.dict[ch]) counts[ch]=(counts[ch]||0)+1; } return counts; }
function analyzeText(){ const text=document.getElementById('inputText').value; const counts=countMatches(text); const chars=Object.keys(counts); const total=chars.reduce((s,k)=>s+counts[k],0); state.last={ text, counts, chars, total }; renderSummary(total, chars.length); renderHighlightedText(text, counts); renderDetectedList(chars, counts); renderModernPreview(text); renderCautionPanel(text); const link=document.getElementById('toConverter'); if(text){ link.hidden=false; link.href=`../kanji-modernizer/?q=${encodeURIComponent(text)}`; link.textContent=t().toConverter; } else { link.hidden=true; } }
function renderSummary(total, unique){ const el=document.getElementById('resultSummary'); el.innerHTML=''; const h=document.createElement('h2'); h.textContent=t().detection; const p=document.createElement('p'); p.textContent=total>0?t().found:t().none; const n=document.createElement('p'); n.textContent=`${t().matches}: ${total} / ${t().unique}: ${unique}`; el.append(h,p,n); }
function renderHighlightedText(text, counts){ const out=document.getElementById('highlightOutput'); out.textContent=''; for(const ch of text){ if(counts[ch]){ const s=document.createElement('span'); s.className='old-kanji-hit'; s.textContent=ch; s.dataset.char=ch; s.onclick=()=>focusCard(ch); out.appendChild(s);} else { out.appendChild(document.createTextNode(ch)); } } }
function renderDetectedList(chars, counts){ const list=document.getElementById('detectedList'); list.textContent=''; for(const ch of chars){ list.appendChild(renderDetectedCard(ch, counts[ch])); } }
function renderDetectedCard(ch, count){ const card=document.createElement('article'); card.className='detected-card'; card.id=`card-${encodeURIComponent(ch)}`; const meta=state.meta[ch]||{}; const modern=Array.isArray(state.dict[ch])?state.dict[ch][0]:state.dict[ch]; const title=document.createElement('h3'); title.textContent=`${ch} → ${modern}`; card.appendChild(title); const lines=[[t().occurrences, count],[t().reading, meta[`reading${state.lang==='ja'?'Ja':'En'}`]],[t().meaning, meta[`meaning${state.lang==='ja'?'Ja':'En'}`]],[t().category, meta.category],[t().usage, meta[`usage${state.lang==='ja'?'Ja':'En'}`]]]; lines.forEach(([k,v])=>{ if(v){ const p=document.createElement('p'); p.textContent=`${k}: ${v}`; card.appendChild(p);} }); const note=renderCompatibilityNote(ch); if(note) card.appendChild(note);
  const actions=document.createElement('div'); actions.className='copy-actions'; const b1=document.createElement('button'); b1.textContent=t().copyOldCard; b1.onclick=()=>copyText(ch); const b2=document.createElement('button'); b2.textContent=t().copyModernCard; b2.onclick=()=>copyText(modern); const a=document.createElement('a'); a.href=`../old-kanji-reference/?q=${encodeURIComponent(ch)}`; a.textContent=t().viewRef; actions.append(b1,b2,a); card.appendChild(actions); return card; }
function renderModernPreview(text){ const out=document.getElementById('modernPreview'); let r=''; for(const ch of text){ const mapped=state.dict[ch]; r += Array.isArray(mapped)?mapped[0]:(mapped||ch); } out.textContent=r; }
function renderCompatibilityNote(ch){ const src=state.compatibility[ch]||getFallbackCompatibilityNote(ch); if(!src) return null; const box=document.createElement('div'); box.className='compatibility-note'; const p=document.createElement('p'); p.textContent=t().rendering; box.appendChild(p); ['summary','copyNote','recommendedCheck'].forEach(k=>{ const v=src[`${k}${state.lang==='ja'?'Ja':'En'}`]; if(v){ const x=document.createElement('p'); x.textContent=v; box.appendChild(x);} }); return box; }
function renderCautionPanel(text){ const el=document.getElementById('cautionPanel'); el.textContent=''; if(!text) return; const h=document.createElement('h2'); h.textContent=t().cautionHead; const p=document.createElement('p'); p.textContent=t().cautionBody; el.append(h,p); }
function setLang(lang){ state.lang=lang; document.documentElement.lang=lang==='ja'?'ja':'en'; document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent=t()[el.dataset.i18n]||el.textContent; }); const ta=document.getElementById('inputText'); ta.placeholder=lang==='ja'?ta.dataset.placeholderJa:ta.dataset.placeholderEn; document.getElementById('langJa').classList.toggle('active', lang==='ja'); document.getElementById('langEn').classList.toggle('active', lang==='en'); if(state.last) analyzeText(); }
async function copyText(text){ try{ if(navigator.clipboard&&window.isSecureContext){ await navigator.clipboard.writeText(text); } else { const ta=document.createElement('textarea'); ta.value=text; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); } showToast(t().copied); } catch {} }
function focusCard(ch){ document.querySelectorAll('.detected-card').forEach(c=>c.classList.remove('selected')); const c=document.getElementById(`card-${encodeURIComponent(ch)}`); if(c){ c.classList.add('selected'); c.scrollIntoView({behavior:'smooth',block:'center'}); }}
function showToast(msg){ const el=document.getElementById('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),1200); }
function t(){ return i18n[state.lang]; }

function syncOkjProRuntimeState() {
  const adapter = window.NicheWorksProEntitlement;
  const panels = document.querySelectorAll('[data-okj-pro-state]');
  panels.forEach((panel) => {
    const features = panel.querySelectorAll('[data-okj-feature-id]');
    let runtimeState = 'billing-unavailable';
    let runtimeActive = false;
    if (adapter && typeof adapter.getFeatureState === 'function') {
      features.forEach((featureEl) => {
        const featureIds = (featureEl.dataset.okjFeatureId || '').split(/\s+/).filter(Boolean);
        featureIds.forEach((featureId) => {
          const featureState = adapter.getFeatureState(featureId);
          runtimeState = featureState?.state || runtimeState;
          runtimeActive = runtimeActive || !!featureState?.active;
          featureEl.dataset.okjRuntimeProState = featureState?.state || runtimeState;
          featureEl.dataset.okjRuntimeProActive = String(!!featureState?.active);
        });
      });
    }
    panel.dataset.okjRuntimeProState = runtimeState;
    panel.dataset.okjRuntimeProActive = String(runtimeActive);
  });
}

(async function init(){ syncOkjProRuntimeState(); await loadData(); await loadMetadata(); await loadCompatibilityNotes(); setLang('ja');
  document.getElementById('analyzeBtn').onclick=analyzeText; document.getElementById('inputText').addEventListener('input', analyzeText);
  document.getElementById('langJa').onclick=()=>setLang('ja'); document.getElementById('langEn').onclick=()=>setLang('en');
  document.getElementById('copyOld').onclick=()=>copyText((state.last?.chars||[]).join(''));
  document.getElementById('copyPairs').onclick=()=>copyText((state.last?.chars||[]).map(ch=>`${ch}\t${Array.isArray(state.dict[ch])?state.dict[ch][0]:state.dict[ch]}`).join('\n'));
  document.getElementById('copyModern').onclick=()=>copyText(document.getElementById('modernPreview').textContent||'');
})();
