#!/usr/bin/env node
/*
  Old Kanji Reference metadata validator

  Usage:
    node tools/old-kanji-reference/validate-meta.js

  Fatal checks:
    - JSON files must be readable
    - meta keys should exist in dict.json (reported as warnings for shared dictionary lag)
    - category must be one of the allowed values
    - popularOrder entries must exist and have verified metadata
    - verified entries must have reading / meaning / category
    - placeholder-like text must not be included

  Non-fatal reports:
    - modern value differences against dict.json are warnings because dict.json still
      contains historical/variant quirks and duplicate mapping sources
    - duplicate metadata keys across meta files are warnings
    - usage note gaps are warnings
    - metadata coverage and missing-meta.txt are development reports
*/

const fs = require("fs");
const path = require("path");

const dir = __dirname;
const dictPath = path.join(dir, "dict.json");
const baseMetaPath = path.join(dir, "meta.json");
const missingPath = path.join(dir, "missing-meta.txt");

const ALLOWED_CATEGORIES = new Set(["popular", "name", "common", "document", "rare"]);
const ALLOWED_DATA_STATUS = new Set(["verified", "needs_review", "pair_only"]);
const ALLOWED_CONFIDENCE = new Set(["high", "medium", "low"]);

const FORBIDDEN_PATTERNS = [
  /準備中/,
  /placeholder/i,
  /pending/i,
  /語による/,
  /\btodo\b/i,
  /TBD/i,
  /旧字体「.*」は現代表記「.*」に対応します/
];

const KNOWN_MODERN_MISMATCH_NOTES = {
  "獨": "dict currently maps 獨 to itself; metadata intentionally normalizes it to 独.",
  "據": "dict has duplicate/variant mapping sources; metadata may intentionally use 拠 depending on entry source."
};

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (err) {
    throw new Error(`Failed to read JSON: ${filePath}\n${err.message}`);
  }
}

function normalizeModern(value) {
  if (Array.isArray(value)) return value.join("、");
  return String(value || "");
}

function hasText(value) {
  return typeof value === "string" && value.trim().length > 0;
}

function scanForbidden(value) {
  if (typeof value !== "string") return null;
  return FORBIDDEN_PATTERNS.find((pattern) => pattern.test(value)) || null;
}

function listMetaFiles() {
  const files = fs.readdirSync(dir)
    .filter((name) => name === "meta.json" || /^meta-extra-.*\.json$/.test(name))
    .sort((a, b) => {
      if (a === "meta.json") return -1;
      if (b === "meta.json") return 1;
      return a.localeCompare(b);
    });
  return files.map((name) => path.join(dir, name));
}

function formatPct(numerator, denominator) {
  if (!denominator) return "0.0%";
  return `${((numerator / denominator) * 100).toFixed(1)}%`;
}

function writeMissingMeta(oldToNew, mergedEntries) {
  const missing = Object.keys(oldToNew).filter((oldChar) => !mergedEntries[oldChar]);
  const lines = [
    "# Old Kanji Reference missing metadata",
    "",
    "Generated by validate-meta.js.",
    "",
    `missing count: ${missing.length}`,
    "",
    ...missing.map((oldChar) => `${oldChar}\t${normalizeModern(oldToNew[oldChar])}`)
  ];
  fs.writeFileSync(missingPath, `${lines.join("\n")}\n`, "utf8");
  return missing;
}

function main() {
  const errors = [];
  const warnings = [];

  const dict = readJson(dictPath);
  const oldToNew = dict.old_to_new || {};
  const metaFiles = listMetaFiles();

  if (!metaFiles.includes(baseMetaPath)) {
    errors.push("meta.json is missing.");
  }

  const mergedEntries = {};
  const seen = new Map();
  const modernGroups = new Map();
  let popularOrder = [];

  for (const filePath of metaFiles) {
    const name = path.basename(filePath);
    const meta = readJson(filePath);
    const entries = meta.entries || {};

    if (name === "meta.json") {
      popularOrder = Array.isArray(meta.popularOrder) ? meta.popularOrder : [];
      if (!popularOrder.length) errors.push("meta.json popularOrder is missing or empty.");
    }

    for (const [oldChar, entry] of Object.entries(entries)) {
      if (seen.has(oldChar)) {
        warnings.push(`Duplicate metadata key: ${oldChar} in ${seen.get(oldChar)} and ${name}. Later file overrides earlier data.`);
      }
      seen.set(oldChar, name);
      mergedEntries[oldChar] = entry;
    }
  }

  for (const [oldChar, entry] of Object.entries(mergedEntries)) {
    const existsInDict = Object.prototype.hasOwnProperty.call(oldToNew, oldChar);
    if (!existsInDict) {
      warnings.push(`Metadata key is not in dict.json yet: ${oldChar}. Keeping existing metadata but excluding it from missing-meta coverage.`);
    }

    const expectedModern = existsInDict ? normalizeModern(oldToNew[oldChar]) : "";
    const modern = hasText(entry.modern) ? entry.modern : expectedModern;
    if (!modernGroups.has(modern)) modernGroups.set(modern, []);
    modernGroups.get(modern).push(oldChar);

    if (existsInDict && hasText(entry.modern) && entry.modern !== expectedModern) {
      const note = KNOWN_MODERN_MISMATCH_NOTES[oldChar] || "Review dict/meta mapping before promoting this entry further.";
      warnings.push(`Modern differs for ${oldChar}: meta=${entry.modern} dict=${expectedModern}. ${note}`);
    }

    if (!hasText(entry.category)) {
      errors.push(`Missing category for ${oldChar}`);
    } else if (!ALLOWED_CATEGORIES.has(entry.category)) {
      errors.push(`Invalid category for ${oldChar}: ${entry.category}`);
    }

    if (!hasText(entry.dataStatus)) {
      errors.push(`Missing dataStatus for ${oldChar}`);
    } else if (!ALLOWED_DATA_STATUS.has(entry.dataStatus)) {
      errors.push(`Invalid dataStatus for ${oldChar}: ${entry.dataStatus}`);
    }

    if (!hasText(entry.confidence)) {
      errors.push(`Missing confidence for ${oldChar}`);
    } else if (!ALLOWED_CONFIDENCE.has(entry.confidence)) {
      errors.push(`Invalid confidence for ${oldChar}: ${entry.confidence}`);
    }

    if (!hasText(entry.sourceNote)) {
      errors.push(`Missing sourceNote for ${oldChar}`);
    }

    if (entry.verified) {
      if (entry.dataStatus !== "verified") {
        errors.push(`Verified entry ${oldChar} must set dataStatus=verified`);
      }
      for (const field of ["readingJa", "readingEn", "meaningJa", "meaningEn"]) {
        if (!hasText(entry[field])) errors.push(`Verified entry ${oldChar} missing ${field}`);
      }
      if (!hasText(entry.usageJa) || !hasText(entry.usageEn)) {
        warnings.push(`Verified entry ${oldChar} has no usage note in one or both languages.`);
      }
    }

    for (const [field, value] of Object.entries(entry)) {
      const matched = scanForbidden(value);
      if (matched) errors.push(`Forbidden placeholder-like text in ${oldChar}.${field}: ${value}`);
    }
  }

  for (const oldChar of popularOrder) {
    const entry = mergedEntries[oldChar];
    if (!entry) {
      errors.push(`popularOrder entry missing metadata: ${oldChar}`);
      continue;
    }
    if (!entry.verified) errors.push(`popularOrder entry is not verified: ${oldChar}`);
    for (const field of ["readingJa", "readingEn", "meaningJa", "meaningEn", "usageJa", "usageEn"]) {
      if (!hasText(entry[field])) errors.push(`popularOrder entry ${oldChar} missing ${field}`);
    }
  }

  const missing = writeMissingMeta(oldToNew, mergedEntries);
  const multiModern = Array.from(modernGroups.entries()).filter(([, olds]) => olds.length > 1);
  const verifiedCount = Object.values(mergedEntries).filter((entry) => entry.verified).length;
  const totalMetaCount = Object.keys(mergedEntries).length;
  const dictCount = Object.keys(oldToNew).length;

  console.log("Old Kanji Reference metadata validation");
  console.log(`dict entries: ${dictCount}`);
  console.log(`meta entries: ${totalMetaCount} (${formatPct(totalMetaCount, dictCount)} coverage)`);
  console.log(`verified entries: ${verifiedCount} (${formatPct(verifiedCount, dictCount)} verified coverage)`);
  console.log(`missing meta entries: ${missing.length}`);
  console.log(`same-modern groups: ${multiModern.length}`);
  console.log(`meta files: ${metaFiles.map((file) => path.basename(file)).join(", ")}`);
  console.log(`missing report: ${path.relative(process.cwd(), missingPath)}`);

  if (multiModern.length) {
    console.log("\nSame-modern groups:");
    multiModern.slice(0, 30).forEach(([modern, olds]) => console.log(`- ${modern}: ${olds.join(" / ")}`));
    if (multiModern.length > 30) console.log(`- ...and ${multiModern.length - 30} more`);
  }

  if (warnings.length) {
    console.warn("\nWarnings:");
    warnings.forEach((warning) => console.warn(`- ${warning}`));
  }

  if (errors.length) {
    console.error("\nErrors:");
    errors.forEach((error) => console.error(`- ${error}`));
    process.exit(1);
  }

  console.log("\nOK: metadata passed validation.");
}

try {
  main();
} catch (err) {
  console.error(err.message || err);
  process.exit(1);
}
