const state = {
  lang: 'ja',
  dict: null,
  metadata: {},
  compatibilityNotes: {},
  shapeNotes: {},
  strokeCounts: {},
  reverseLookup: {},
  compared: []
};

const I18N = {
  ja: {
    title: '異体字比較ツール', description: '見た目が近い漢字・旧字体・異体字を並べて、Unicode、HTMLエンティティ、字形差、表示環境の注意を確認するブラウザ内ツールです。', inputLabel: '比較する文字を入力', compareBtn: '比較する', copyComparison: '比較結果をコピー', copyCsv: 'CSV形式でコピー', presetTitle: 'プリセット比較', result: '比較結果', comparedChars: '比較文字数', compatibilityCount: '互換漢字', supplementaryCount: '補助平面文字', mappingCount: '旧字体対応あり', renderingCount: '表示注意あり', glyphComparison: '字形比較', differenceHints: '見分けるポイント', relatedLinks: '関連リンク', unicodeCheckerLink: 'Unicode漢字チェッカーでも確認する', cautionTitle: '異体字比較時の注意', cautionText: 'このツールは字形・文字コード・表示環境の違いを確認するための参考ツールです。氏名、地名、戸籍、登記、契約書類、システム登録などで使う場合は、実際の登録字体・保存形式・利用先システムでの表示を確認してください。ここで表示される候補は、法的な有効性や登録可否を判断するものではありません。', privacyNote: '入力内容はブラウザ内で処理され、外部APIには送信しません。アクセス解析や広告タグが読み込まれる場合があります。', copied: 'コピーしました', viewOldRef: '旧字体一覧で詳しく見る', oldToModern: '旧 → 新', modernCandidates: '候補', renderingNote: '表示注意', stroke: '画数', reading: '読み', meaning: '意味', category: '分類', serif: 'Serif', sans: 'Sans-serif', system: 'System', copyChar: '文字をコピー', copyUnicode: 'Unicodeをコピー', copyHex: 'HTML hexをコピー', copyDec: 'HTML decimalをコピー', copyUtf16: 'UTF-16をコピー', genericHint: '字形の違いはフォントや表示環境によって見え方が変わる場合があります。拡大表示とUnicodeをあわせて確認してください。'
  },
  en: {
    title: 'Variant Kanji Compare', description: 'A browser-side tool for comparing similar-looking kanji, old forms, and variants by Unicode, HTML entities, glyph differences, and rendering notes.', inputLabel: 'Enter characters to compare', compareBtn: 'Compare characters', copyComparison: 'Copy comparison', copyCsv: 'Copy as CSV', presetTitle: 'Preset comparisons', result: 'Comparison result', comparedChars: 'Compared characters', compatibilityCount: 'Compatibility ideographs', supplementaryCount: 'Supplementary-plane characters', mappingCount: 'Has old/modern mapping', renderingCount: 'Has rendering note', glyphComparison: 'Glyph comparison', differenceHints: 'Comparison hints', relatedLinks: 'Related links', unicodeCheckerLink: 'Check in Unicode Kanji Checker', cautionTitle: 'Important note for variant comparison', cautionText: 'This tool is a reference aid for comparing glyphs, character codes, and rendering behavior. For names, place names, family registers, registrations, contracts, or system records, confirm the actual registered glyph, storage format, and rendering in the target system. The candidates shown here do not determine legal validity or registration availability.', privacyNote: 'Input is processed in the browser and is not sent to an external API. Analytics or ad tags may be loaded on the page.', copied: 'Copied', viewOldRef: 'View in Old Kanji Reference', oldToModern: 'Old → Modern', modernCandidates: 'Candidates', renderingNote: 'Rendering note', stroke: 'Stroke count', reading: 'Reading', meaning: 'Meaning', category: 'Category', serif: 'Serif', sans: 'Sans-serif', system: 'System', copyChar: 'Copy character', copyUnicode: 'Copy Unicode', copyHex: 'Copy HTML hex', copyDec: 'Copy HTML decimal', copyUtf16: 'Copy UTF-16', genericHint: 'Glyph differences may vary by font or environment. Compare the enlarged glyphs together with Unicode code points.'
  }
};

const PRESETS = ['崎 﨑', '高 髙', '吉 𠮷', '辺 邊 邉', '斎 齋 齊', '浜 濱', '沢 澤', '国 國', '学 學'];

async function loadData() { state.dict = await fetch('./../old-kanji-reference/dict.json').then((r) => r.json()).catch(() => ({ old_to_new: {} })); state.reverseLookup = buildReverseLookupFromOldToNew(state.dict.old_to_new || {}); state.metadata = await loadMetadata(); state.compatibilityNotes = await loadCompatibilityNotes(); state.shapeNotes = await loadShapeNotes(); state.strokeCounts = await loadStrokeCounts(); }
function buildReverseLookupFromOldToNew(oldToNew) { const reverse = {}; Object.entries(oldToNew).forEach(([oldCh, modern]) => { if (!reverse[modern]) reverse[modern] = []; reverse[modern].push(oldCh); }); return reverse; }
async function loadMetadata() { const files = ['meta.json', 'meta-extra-2.json', 'meta-extra-3.json', 'meta-extra-4.json', 'meta-extra-5.json', 'meta-extra-6.json']; const merged = {}; for (const file of files) { try { const data = await fetch(`./../old-kanji-reference/${file}`).then((r) => r.json()); Object.assign(merged, data); } catch (e) {} } return merged; }
async function loadCompatibilityNotes() { return fetch('./../old-kanji-reference/compatibility-notes.json').then((r) => r.json()).catch(() => ({})); }
async function loadShapeNotes() { return fetch('./../old-kanji-reference/shape-notes.json').then((r) => r.json()).catch(() => ({})); }
async function loadStrokeCounts() { return fetch('./../old-kanji-reference/stroke-counts.json').then((r) => r.json()).catch(() => ({})); }
function parseInputCharacters(text) { const cleaned = text.replace(/[\s,\/、，]+/g, ''); return [...new Set(Array.from(cleaned))]; }
function compareCharacters(chars) { return chars.map((ch) => { const cp = ch.codePointAt(0); const unicode = `U+${cp.toString(16).toUpperCase()}`; const info = { ch, cp, unicode, htmlHex: `&#x${cp.toString(16).toUpperCase()};`, htmlDec: `&#${cp};`, utf16: Array.from(ch).map((c) => c.charCodeAt(0).toString(16).toUpperCase().padStart(4, '0')).join(' '), oldToModern: state.dict.old_to_new?.[ch] || null, modernCandidates: state.reverseLookup[ch] || [], meta: state.metadata[ch] || null, shape: state.shapeNotes[ch] || null, stroke: state.strokeCounts[ch] || null, compatibility: renderCompatibilityNote(ch, cp) }; return info; }); }
function renderSummary(items) { const t = I18N[state.lang]; const section = document.getElementById('summarySection'); const compatibilityCount = items.filter((x) => x.compatibility).length; const supplementaryCount = items.filter((x) => x.cp > 0xFFFF).length; const mappingCount = items.filter((x) => x.oldToModern || x.modernCandidates.length).length; section.textContent = `${t.result} | ${t.comparedChars}: ${items.length} | ${t.compatibilityCount}: ${compatibilityCount} | ${t.supplementaryCount}: ${supplementaryCount} | ${t.mappingCount}: ${mappingCount} | ${t.renderingCount}: ${compatibilityCount}`; section.hidden = false; }
function renderComparisonGrid(items) { const grid = document.getElementById('comparisonGrid'); grid.innerHTML = ''; items.forEach((item) => grid.appendChild(renderCharacterColumn(item))); }
function renderCharacterColumn(item) { const t = I18N[state.lang]; const card = document.createElement('article'); card.className = 'variant-card'; const h3 = document.createElement('h3'); h3.textContent = item.ch; card.appendChild(h3); card.appendChild(renderGlyphRows(item.ch)); const codeGrid = document.createElement('div'); codeGrid.className = 'code-grid'; [['Unicode', item.unicode], ['HTML hex', item.htmlHex], ['HTML decimal', item.htmlDec], ['UTF-16', item.utf16]].forEach(([k,v]) => { const row = document.createElement('div'); row.className = 'code-row'; const kEl = document.createElement('strong'); kEl.textContent = k; const vEl = document.createElement('code'); vEl.textContent = v; row.append(kEl, vEl); codeGrid.appendChild(row); }); card.appendChild(codeGrid);
  const details = document.createElement('p');
  const parts = [];
  if (item.oldToModern) parts.push(`${t.oldToModern}: ${item.oldToModern}`);
  if (item.modernCandidates.length) parts.push(`${t.modernCandidates}: ${item.modernCandidates.join(' / ')}`);
  if (item.meta?.reading) parts.push(`${t.reading}: ${item.meta.reading}`);
  if (item.meta?.meaning) parts.push(`${t.meaning}: ${item.meta.meaning}`);
  if (item.meta?.category) parts.push(`${t.category}: ${item.meta.category}`);
  if (item.shape?.summary) parts.push(item.shape.summary);
  if (item.stroke) parts.push(`${t.stroke}: ${item.stroke}`);
  details.textContent = parts.join(' | ');
  card.appendChild(details);
  if (item.compatibility) { const note = document.createElement('div'); note.className = 'compatibility-note'; note.textContent = `${t.renderingNote}: ${item.compatibility}`; card.appendChild(note); }
  const link = document.createElement('a'); const refChar = item.modernCandidates[0] || item.ch; link.href = `../old-kanji-reference/?q=${encodeURIComponent(refChar)}`; link.textContent = t.viewOldRef; card.appendChild(link);
  const actions = document.createElement('div'); actions.className = 'copy-actions';
  [[t.copyChar,item.ch],[t.copyUnicode,item.unicode],[t.copyHex,item.htmlHex],[t.copyDec,item.htmlDec],[t.copyUtf16,item.utf16]].forEach(([label,val]) => { const b = document.createElement('button'); b.type='button'; b.textContent = label; b.addEventListener('click', () => copyText(val)); actions.appendChild(b); });
  card.appendChild(actions); return card; }
function renderGlyphRows(ch) { const t = I18N[state.lang]; const wrap = document.createElement('section'); const heading = document.createElement('h4'); heading.textContent = t.glyphComparison; wrap.appendChild(heading); const grid = document.createElement('div'); grid.className = 'glyph-font-grid'; [[t.serif,'glyph-serif'],[t.sans,'glyph-sans'],[t.system,'glyph-system']].forEach(([name,cls])=>{ const row=document.createElement('div'); row.className='glyph-font-row'; const n=document.createElement('strong'); n.textContent=name; const glyph=document.createElement('div'); glyph.className=`glyph-large ${cls}`; glyph.textContent=ch; row.append(n,glyph); grid.appendChild(row);}); wrap.appendChild(grid); return wrap; }
function renderDifferenceHints(items) { const t = I18N[state.lang]; const section = document.getElementById('differenceHints'); if (items.length < 2) { section.hidden = true; return; } const notes = items.map((x) => x.shape?.summary).filter(Boolean); section.innerHTML = `<h2>${t.differenceHints}</h2><p>${notes[0] || t.genericHint}</p>`; section.hidden = false; }
function renderCompatibilityNote(ch, codePoint) { const explicit = state.compatibilityNotes[ch]; if (explicit) { return [explicit.summary, explicit.note, explicit.technical_note, explicit.recommended_check].filter(Boolean).join(' / '); } if (codePoint >= 0xF900 && codePoint <= 0xFAFF) return 'CJK Compatibility Ideograph range'; if (codePoint > 0xFFFF) return 'Supplementary Plane character'; if ((codePoint >= 0xFE00 && codePoint <= 0xFE0F) || (codePoint >= 0xE0100 && codePoint <= 0xE01EF)) return 'Variation Selector range'; return ''; }
function renderCautionPanel(hasInput) { const panel = document.getElementById('cautionSection'); if (!hasInput) { panel.hidden = true; return; } const t = I18N[state.lang]; panel.textContent = `${t.cautionTitle}: ${t.cautionText}`; panel.hidden = false; }
function setLang(lang) { state.lang = lang; document.documentElement.lang = lang === 'ja' ? 'ja' : 'en'; document.querySelectorAll('.nw-lang-btn').forEach((btn) => btn.classList.toggle('active', btn.dataset.lang === lang)); document.querySelectorAll('[data-i18n]').forEach((el) => { const key = el.dataset.i18n; if (I18N[lang][key]) el.textContent = I18N[lang][key]; }); const input = document.getElementById('inputText'); input.placeholder = lang === 'ja' ? input.dataset.placeholderJa : input.dataset.placeholderEn; if (state.compared.length) renderAll(state.compared.map((x) => x.ch)); }
async function copyText(value) { if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(value); } else { const ta = document.createElement('textarea'); ta.value = value; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); } const toast = document.getElementById('toast'); toast.textContent = I18N[state.lang].copied; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1200); }
function toCsv(items) { const header = ['character','unicode','html_hex','html_dec','utf16']; const rows = items.map((x) => [x.ch, x.unicode, x.htmlHex, x.htmlDec, x.utf16]); return [header, ...rows].map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n'); }
function renderAll(chars) { const uniqueChars = parseInputCharacters(chars.join('')); state.compared = compareCharacters(uniqueChars); document.getElementById('unicodeCheckerWrap').hidden = uniqueChars.length === 0; document.getElementById('unicodeCheckerLink').href = `../unicode-kanji-checker/?q=${encodeURIComponent(uniqueChars.join(''))}`; if (uniqueChars.length === 0) { document.getElementById('summarySection').hidden = true; document.getElementById('comparisonGrid').innerHTML = ''; renderCautionPanel(false); return; } renderSummary(state.compared); renderComparisonGrid(state.compared); renderDifferenceHints(state.compared); renderCautionPanel(true); }

document.addEventListener('DOMContentLoaded', async () => { await loadData(); const input = document.getElementById('inputText'); const presetWrap = document.getElementById('presetButtons'); PRESETS.forEach((preset) => { const btn = document.createElement('button'); btn.type = 'button'; btn.textContent = preset.replace(/ /g, ' / '); btn.addEventListener('click', () => { input.value = preset; renderAll(parseInputCharacters(preset)); }); presetWrap.appendChild(btn); }); document.getElementById('compareBtn').addEventListener('click', () => renderAll(parseInputCharacters(input.value))); input.addEventListener('input', () => renderAll(parseInputCharacters(input.value))); document.getElementById('copyAllBtn').addEventListener('click', () => copyText(state.compared.map((x) => `${x.ch} ${x.unicode} ${x.htmlHex} ${x.htmlDec} ${x.utf16}`).join('\n'))); document.getElementById('copyCsvBtn').addEventListener('click', () => copyText(toCsv(state.compared))); document.querySelectorAll('.nw-lang-btn').forEach((btn) => btn.addEventListener('click', () => setLang(btn.dataset.lang))); setLang('ja'); });
