(() => {
  const STRIPE='https://buy.stripe.com/bJe14p2QV1M13dz5kjcV208';
  const KEY='nw_pro_moving_lease_final_check';
  const $=(id)=>document.getElementById(id);
  const isPro=()=>localStorage.getItem(KEY)==='1'||!!localStorage.getItem('nw_pro_key');
  const PRO_MSG='Pro限定機能です。購入後に ?pro=1 で解放してください。';
  function activate(){const u=new URL(location.href);if(u.searchParams.get('pro')==='1'){localStorage.setItem(KEY,'1');u.searchParams.delete('pro');history.replaceState({},'',u.toString())}}
  function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2400)}
  function proBox(){if(!$('nwProBox')){const s=document.createElement('section');s.id='nwProBox';s.className='notice-card';s.innerHTML=`<h2>Pro</h2><p id="nwProMsg"></p><p><a href="${STRIPE}" target="_blank" rel="noopener">Unlock Pro / Proを購入</a></p><p>After payment, open this page with ?pro=1.</p>`;document.querySelector('main')?.insertBefore(s,$('result')||null)}$('nwProMsg').textContent=isPro()?'Pro解放済み：TXT保存と印刷/PDF保存が使えます。':'Pro機能：TXT保存・印刷/PDF保存。購入後にこの端末で解放されます。'}
  function needPro(e){if(isPro())return true;e?.preventDefault?.();e?.stopImmediatePropagation?.();proBox();toast(PRO_MSG);return false}
  const TASKS={common:[['c1','郵便転送届、宅配、定期配送の転送・停止を確認した','郵便・配送'],['c2','銀行、クレカ、保険、主要通販、勤務先などの住所変更先を把握した','住所変更'],['c3','契約書、本人確認書類、鍵、重要書類を一箇所にまとめた','紛失防止'],['c4','粗大ごみ、残置物、不用品回収の予定を確認した','残置物'],['c5','電気・ガス・水道・ネット回線の停止/移転日と返却物を確認した','継続課金']],rental:[['r1','退去通知の控え、管理会社からの案内、立会い日時を保存した','退去通知'],['r2','退去立会い当日の持ち物、鍵本数、返却方法を確認した','鍵返却'],['r3','鍵本数と鍵の状態を写真で記録した','返却記録'],['r4','室内全体、床、壁、水回り、設備、既存傷を写真で記録した','写真記録'],['r5','電気・ガス・水道メーターの写真を撮る準備をした','メーター'],['r6','火災保険の解約または住所変更の要否を確認した','保険'],['r7','敷金・保証金などの返金先口座、退去後の連絡先を整理した','精算連絡'],['r8','管理会社へ提出する書類・返却物・連絡事項を確認した','提出物'],['r9','エアコン、照明、備品、設備など残す物/外す物を契約内容と照合した','設備確認'],['r10','原状回復や修繕費の判断は契約書・管理会社案内で確認する前提にした','契約確認']],owned:[['o1','ブレーカー、止水栓、ガス元栓など停止ポイントを確認した','事故防止'],['o2','固定資産税や自治体書類の送付先を確認した','税・書類'],['o3','火災保険・地震保険の住所変更または契約見直しを確認した','保険'],['o4','自治会、管理組合、近隣、管理会社への連絡が必要か確認した','連絡'],['o5','空き家になる場合の換気、通水、郵便物、草木、見回り方法を決めた','空き家管理'],['o6','売却・賃貸化・引渡し予定がある場合の書類と鍵管理を確認した','引渡し'],['o7','電気・ガス・水道・固定回線・管理費など継続課金を棚卸しした','継続課金'],['o8','メーター、室内、外回り、設備状態の写真を残す準備をした','写真記録'],['o9','転出・転入など自治体手続きの期限と必要書類を確認した','自治体']]};
  const LAST='nw_moving_final_last_v1';
  let armed=false;
  function fmt(v){if(!v)return'';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?'':v}
  function type(){return $('homeType').value==='owned'?'owned':'rental'}
  function label(t){return t==='rental'?'賃貸':'持ち家'}
  function tasks(t){return TASKS.common.concat(TASKS[t]).map(x=>({id:x[0],text:x[1],meta:x[2]}))}
  function ctx(){const date=fmt($('moveDate').value);if(!date)return null;const ht=type();return{date,homeType:ht,key:`nw_moving_final_v1:${date}:${ht}`,tasks:tasks(ht)}}
  function load(k){try{return JSON.parse(localStorage.getItem(k)||'{}')||{}}catch(_){return{}}}
  function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
  function progress(ts,c){const done=ts.filter(t=>c[t.id]).length,p=ts.length?Math.round(done/ts.length*100):0;$('progressFill').style.width=p+'%';$('progressText').textContent=`${done} / ${ts.length} 完了`;['btnClear','btnCopyTxt','btnSaveTxt','btnPrint'].forEach(id=>{if($(id))$(id).disabled=!ts.length})}
  function render(){const c=ctx();if(!c)return toast('退去日 / 引っ越し日を入力してください。');const checks=load(c.key);$('resultMeta').textContent=`${c.date} / ${label(c.homeType)}（この条件で保存）`;$('taskList').textContent='';c.tasks.forEach(t=>{const li=document.createElement('li');li.className='task-item';const row=document.createElement('label');row.className='task';const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!checks[t.id];cb.addEventListener('change',()=>{checks[t.id]=cb.checked;save(c.key,checks);progress(c.tasks,checks)});const body=document.createElement('div');body.innerHTML=`<div class="ttext"></div><div class="tmeta">カテゴリ: ${t.meta}</div>`;body.querySelector('.ttext').textContent=t.text;row.append(cb,body);li.appendChild(row);$('taskList').appendChild(li)});$('result').hidden=false;localStorage.setItem(LAST,JSON.stringify({dateStr:c.date,homeType:c.homeType}));progress(c.tasks,checks)}
  function clearChecks(){const c=ctx();if(!c)return toast('退去日 / 引っ越し日を入力してください。');if(!armed){armed=true;$('btnClear').textContent='もう一度押すと全解除';toast('全解除する場合はもう一度押してください。');setTimeout(()=>{armed=false;$('btnClear').textContent='チェック全解除'},4500);return}localStorage.removeItem(c.key);armed=false;render();toast('チェックを全解除しました。')}
  function text(){const c=ctx();if(!c)return'';const ch=load(c.key),done=c.tasks.filter(t=>ch[t.id]).length;return ['Moving / Lease Final Check',`日付: ${c.date}`,`住居タイプ: ${label(c.homeType)}`,`進捗: ${done} / ${c.tasks.length}`,'','チェック項目:',...c.tasks.map(t=>`${ch[t.id]?'[x]':'[ ]'} ${t.text}（${t.meta}）`),'','注意: 一般的な確認用です。契約内容や退去精算結果を保証しません。'].join('\n')}
  async function copyTxt(){const out=text();if(!out)return toast('先にチェックリストを表示してください。');try{await navigator.clipboard.writeText(out);toast('TXTをコピーしました。')}catch(_){toast('コピーできませんでした。')}}
  function saveTxt(e){if(!needPro(e))return;const out=text(),c=ctx();if(!out||!c)return toast('先にチェックリストを表示してください。');const b=new Blob([out],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`moving-lease-final-check-${c.date}-${c.homeType}.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);toast('TXTを保存しました。')}
  function print(e){if(!needPro(e))return;if($('result').hidden)return toast('先にチェックリストを表示してください。');window.print()}
  function reset(){ $('moveDate').value='';$('homeType').value='rental';$('result').hidden=true;$('taskList').textContent='';$('progressFill').style.width='0%';$('progressText').textContent='0 / 0 完了';toast('入力欄をリセットしました。')}
  function init(){activate();proBox();$('btnGenerate').addEventListener('click',render);$('btnClear').addEventListener('click',clearChecks);$('btnReset').addEventListener('click',reset);$('btnDeleteCurrentData').addEventListener('click',()=>{const c=ctx();if(c)localStorage.removeItem(c.key);render()});$('btnDeleteLastData').addEventListener('click',()=>{localStorage.removeItem(LAST);toast('前回条件の保存を削除しました。')});$('btnCopyTxt').addEventListener('click',copyTxt);$('btnSaveTxt').addEventListener('click',saveTxt,true);$('btnPrint').addEventListener('click',print,true);try{const last=JSON.parse(localStorage.getItem(LAST)||'null');if(last){$('moveDate').value=last.dateStr||'';$('homeType').value=last.homeType||'rental'}}catch(_){}}
  document.addEventListener('DOMContentLoaded',init);
})();
