(()=>{
const $=id=>document.getElementById(id),root=document.documentElement;
const micButton=$('micButton'),stopMicButton=$('stopMicButton'),micStatus=$('micStatus'),voiceActivity=$('voiceActivity'),volumeBar=$('volumeBar'),volumeValue=$('volumeValue'),pitchValue=$('pitchValue'),noteValue=$('noteValue'),canvas=$('spectrumCanvas'),ctx=canvas.getContext('2d'),snapshotButton=$('snapshotButton'),snapshotCount=$('snapshotCount'),snapshotItems=$('snapshotItems'),clearSnapshotsBtn=$('clearSnapshots'),segmentStart=$('segmentStart'),segmentStop=$('segmentStop'),segmentResult=$('segmentResult'),resetButton=$('resetButton');
const FFT_SIZE=2048,ACTIVITY_THRESHOLD=.06,SNAP_MAX=20,LANG_KEY='nw_lang';
const MSG={ja:{starting:'マイクを起動しています…',micOn:'マイクは有効です。停止する場合は Stop Mic を押してください。',micOff:'マイクを停止しました。',denied:'マイク権限が拒否されました。ブラウザ設定からこのサイトのマイク許可を確認してください。',error:'マイクの起動に失敗しました。別のアプリが使用中でないか、端末設定を確認してください。',unsupported:'このブラウザは音声入力に対応していない可能性があります。',empty:'スナップショットはまだありません。',clearArmed:'もう一度押すと、すべての数値スナップショットを削除します。',cleared:'スナップショットを削除しました。',recording:'記録中…',tooShort:'短すぎます（1秒以上）',title:'区間解析結果',duration:'区間長',avgVol:'平均音量',avgHz:'平均周波数',stability:'安定度',noise:'ノイズ',low:'Low',mid:'Mid',high:'High',delete:'削除',peak:'ピーク',active:'active',silent:'silent'},en:{starting:'Starting microphone...',micOn:'Microphone is active. Press Stop Mic to turn it off.',micOff:'Microphone stopped.',denied:"Microphone permission was denied. Check this site's microphone permission in your browser settings.",error:'Failed to start microphone. Check whether another app is using it or whether device settings block access.',unsupported:'Your browser may not support audio input features.',empty:'No snapshots yet.',clearArmed:'Press again to delete all number snapshots.',cleared:'Snapshots cleared.',recording:'Recording...',tooShort:'Too short (needs 1s+).',title:'Segment Result',duration:'Duration',avgVol:'Avg Loudness',avgHz:'Avg Pitch',stability:'Stability',noise:'Noise Level',low:'Low',mid:'Mid',high:'High',delete:'Delete',peak:'Peak',active:'active',silent:'silent'}};
let lang=detectLang(),audioCtx=null,analyser=null,sourceNode=null,mediaStream=null,timeData=null,freqData=null,rafId=null,lastActive=false,starting=false,snapshots=[],clearArmed=false,clearTimer=null,segActive=false,segStartTs=0,segVol=[],segHz=[],segActiveFrames=0,segTotalFrames=0;
function detectLang(){try{const v=localStorage.getItem(LANG_KEY);if(v==='ja'||v==='en')return v}catch{}return (navigator.language||'').toLowerCase().startsWith('ja')?'ja':'en'}
function applyLang(v){lang=v==='en'?'en':'ja';root.dataset.lang=lang;document.documentElement.lang=lang;try{localStorage.setItem(LANG_KEY,lang)}catch{}document.querySelectorAll('[data-i18n]').forEach(el=>{el.style.display=el.dataset.i18n===lang?'':'none'});document.querySelectorAll('[data-lang-switch]').forEach(b=>b.classList.toggle('active',b.dataset.langSwitch===lang));renderSnapshots();if(!segmentResult.classList.contains('hidden')&&!segActive&&segVol.length)renderSegmentResult();if(segActive)segmentResult.textContent=MSG[lang].recording}
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}function rmsToDb(r){return clamp(20*Math.log10(Math.max(r,1e-6)),-60,0)}
function computeRMS(buf){let s=0;for(let i=0;i<buf.length;i++)s+=buf[i]*buf[i];return Math.sqrt(s/buf.length)}
function detectPitchACF(buf,sr){let rms=computeRMS(buf);if(rms<.008)return null;let r1=0,r2=buf.length-1;for(let i=0;i<buf.length/2;i++){if(Math.abs(buf[i])<.02){r1=i;break}}for(let i=1;i<buf.length/2;i++){if(Math.abs(buf[buf.length-i])<.02){r2=buf.length-i;break}}if(r2-r1<256){r1=0;r2=buf.length-1}const b=buf.slice(r1,r2),n=b.length,c=new Array(n).fill(0);for(let i=0;i<n;i++){let sum=0;for(let j=0;j<n-i;j++)sum+=b[j]*b[j+i];c[i]=sum}let d=0;while(d<n-1&&c[d]>c[d+1])d++;let m=-1,p=-1;for(let i=d;i<n;i++){if(c[i]>m){m=c[i];p=i}}if(p<=0)return null;const x1=c[p-1]||0,x2=c[p]||0,x3=c[p+1]||0,a=(x1+x3-2*x2)/2,bb=(x3-x1)/2;let t=p;if(a!==0)t=p-bb/(2*a);const hz=sr/t;return Number.isFinite(hz)&&hz>=60&&hz<=1200?hz:null}
function hzToNote(hz){if(!hz)return'--';const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],m=69+Math.round(12*Math.log2(hz/440));return names[(m+1200)%12]+(Math.floor(m/12)-1)}
function peak(bins,sr){let mi=0,mv=-1;for(let i=0;i<bins.length;i++){if(bins[i]>mv){mv=bins[i];mi=i}}return mv<=0?{peakHz:null}:{peakHz:mi*(sr/2)/bins.length}}
function fmt(ts){const d=new Date(ts);return [d.getHours(),d.getMinutes(),d.getSeconds()].map(v=>String(v).padStart(2,'0')).join(':')}
function running(){return !!(audioCtx&&analyser&&mediaStream)}function status(t,type='info'){if(!micStatus)return;micStatus.textContent=t;micStatus.className='mic-status '+type}function hideStatus(){if(!micStatus)return;micStatus.textContent='';micStatus.className='mic-status hidden'}
function setVoice(a){voiceActivity.classList.toggle('active',a);voiceActivity.classList.toggle('silent',!a);lastActive=a}function setVol(db){volumeValue.textContent=Math.round(db)+' dB';volumeBar.style.width=clamp((db+60)/60*100,0,100)+'%'}function setPitch(hz){pitchValue.textContent=hz?Math.round(hz)+' Hz':'-- Hz';noteValue.textContent=hz?hzToNote(hz):'--'}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(200,Math.floor(r.width*d)),h=Math.max(120,Math.floor(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function resetMeter(){setVoice(false);setVol(-60);setPitch(null);resizeCanvas();ctx.clearRect(0,0,canvas.width,canvas.height)}
function controls(){const r=running();micButton.disabled=r||starting;micButton.classList.toggle('hidden',r);micButton.classList.toggle('is-pending',starting);micButton.setAttribute('aria-disabled',String(r||starting));if(stopMicButton){stopMicButton.disabled=!r;stopMicButton.classList.toggle('hidden',!r);stopMicButton.setAttribute('aria-disabled',String(!r))}snapshotButton.disabled=!r;segmentStart.disabled=!r||segActive;if(!r)segmentStop.disabled=true;resetButton.classList.toggle('hidden',!r&&!snapshots.length&&segmentResult.classList.contains('hidden'))}
function draw(bins){resizeCanvas();const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const bars=w<420?20:w<700?32:48,step=Math.max(1,Math.floor(bins.length/bars)),bw=w/bars;ctx.fillStyle='#111827';for(let i=0;i<bars;i++){let max=0;for(let j=i*step;j<Math.min(bins.length,i*step+step);j++)max=Math.max(max,bins[j]);const bh=max/255*(h-10);ctx.fillRect(i*bw+bw*.18,h-bh,bw*.64,bh)}ctx.strokeStyle='#e5e7eb';ctx.lineWidth=Math.max(1,window.devicePixelRatio||1);ctx.strokeRect(.5,.5,w-1,h-1)}
function renderSnapshots(){snapshotCount.textContent=String(snapshots.length);snapshotItems.textContent='';if(!snapshots.length){const p=document.createElement('p');p.className='empty-note';p.textContent=MSG[lang].empty;snapshotItems.appendChild(p);controls();return}snapshots.forEach(s=>{const card=document.createElement('div');card.className='snapshot-card';const meta=document.createElement('div');meta.className='meta';meta.textContent=`${fmt(s.ts)} • ${s.active?MSG[lang].active:MSG[lang].silent}`;card.appendChild(meta);const vals=document.createElement('div');vals.className='vals';[`Volume: ${Math.round(s.db)} dB`,`Pitch: ${s.hz?Math.round(s.hz)+' Hz ('+s.note+')':'--'}`,`${MSG[lang].peak}: ${s.peakHz?Math.round(s.peakHz)+' Hz':'--'}`].forEach(t=>{const d=document.createElement('div');d.textContent=t;vals.appendChild(d)});card.appendChild(vals);const actions=document.createElement('div');actions.className='actions';const del=document.createElement('button');del.type='button';del.className='delete';del.textContent=MSG[lang].delete;del.addEventListener('click',()=>{snapshots=snapshots.filter(x=>x.id!==s.id);renderSnapshots()});actions.appendChild(del);card.appendChild(actions);snapshotItems.appendChild(card)});controls()}
function stars(vals){const hz=vals.filter(v=>typeof v==='number'&&Number.isFinite(v));if(hz.length<5)return 1;const mean=hz.reduce((a,b)=>a+b,0)/hz.length,std=Math.sqrt(hz.reduce((a,b)=>a+(b-mean)**2,0)/hz.length),ratio=std/Math.max(mean,1e-6);return ratio<.01?5:ratio<.02?4:ratio<.04?3:ratio<.07?2:1}
function addRow(parent,label,val,muted=false){const d=document.createElement('div');if(muted){const s=document.createElement('span');s.className='muted';s.textContent=label;d.appendChild(s)}else d.textContent=`${label}: ${val}`;parent.appendChild(d)}
function renderSegmentResult(){const sec=(Date.now()-segStartTs)/1000;segmentResult.textContent='';segmentResult.classList.remove('hidden');if(sec<1){segmentResult.textContent=MSG[lang].tooShort;controls();return}const avg=segVol.reduce((a,b)=>a+b,0)/Math.max(1,segVol.length),hzVals=segHz.filter(v=>typeof v==='number'&&Number.isFinite(v)),avgHz=hzVals.length?hzVals.reduce((a,b)=>a+b,0)/hzVals.length:null,st=stars(segHz),activeRate=segTotalFrames?segActiveFrames/segTotalFrames:0,noise=avg>-28?'High':avg>-38||activeRate>.35?'Mid':'Low',nl=noise==='Low'?MSG[lang].low:noise==='Mid'?MSG[lang].mid:MSG[lang].high;addRow(segmentResult,MSG[lang].title,'',true);addRow(segmentResult,MSG[lang].duration,sec.toFixed(1)+'s');addRow(segmentResult,MSG[lang].avgVol,Math.round(avg)+' dB');addRow(segmentResult,MSG[lang].avgHz,avgHz?Math.round(avgHz)+' Hz':'--');addRow(segmentResult,MSG[lang].stability,'★'.repeat(st)+'☆'.repeat(5-st));addRow(segmentResult,MSG[lang].noise,nl);controls()}
function tick(){if(!analyser||!audioCtx||!timeData||!freqData)return;analyser.getFloatTimeDomainData(timeData);analyser.getByteFrequencyData(freqData);const rms=computeRMS(timeData),db=rmsToDb(rms),active=rms>=ACTIVITY_THRESHOLD,hz=rms>=.01?detectPitchACF(timeData,audioCtx.sampleRate):null;setVol(db);if(active!==lastActive)setVoice(active);setPitch(hz);draw(freqData);if(segActive){segTotalFrames++;if(active)segActiveFrames++;segVol.push(db);segHz.push(hz)}rafId=requestAnimationFrame(tick)}
function cleanup(){if(rafId)cancelAnimationFrame(rafId);rafId=null;if(sourceNode){try{sourceNode.disconnect()}catch{}}sourceNode=null;if(mediaStream){mediaStream.getTracks().forEach(t=>{try{t.stop()}catch{}})}mediaStream=null;if(audioCtx){const c=audioCtx;try{if(c.state!=='closed')c.close().catch(()=>{})}catch{}}audioCtx=null;analyser=null;timeData=null;freqData=null}
async function startMic(){if(starting||running())return;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){status(MSG[lang].unsupported,'error');controls();return}const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx){status(MSG[lang].unsupported,'error');controls();return}starting=true;status(MSG[lang].starting,'info');controls();try{audioCtx=new Ctx();mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});analyser=audioCtx.createAnalyser();analyser.fftSize=FFT_SIZE;analyser.smoothingTimeConstant=.85;sourceNode=audioCtx.createMediaStreamSource(mediaStream);sourceNode.connect(analyser);timeData=new Float32Array(analyser.fftSize);freqData=new Uint8Array(analyser.frequencyBinCount);resetMeter();if(rafId)cancelAnimationFrame(rafId);rafId=requestAnimationFrame(tick);status(MSG[lang].micOn,'ok')}catch(e){const n=e&&e.name?e.name:'';status((n==='NotAllowedError'||n==='PermissionDeniedError')?MSG[lang].denied:MSG[lang].error,'error');cleanup();resetMeter()}finally{starting=false;controls()}}
function stopMic(opts={}){cleanup();segActive=false;segmentStop.disabled=true;segmentStart.disabled=true;resetMeter();if(opts.show!==false)status(MSG[lang].micOff,'info');controls()}
function takeSnapshot(){if(!running())return;analyser.getFloatTimeDomainData(timeData);analyser.getByteFrequencyData(freqData);const rms=computeRMS(timeData),db=rmsToDb(rms),active=rms>=ACTIVITY_THRESHOLD,hz=rms>=.01?detectPitchACF(timeData,audioCtx.sampleRate):null,pk=peak(freqData,audioCtx.sampleRate);snapshots.push({id:Date.now()+'-'+Math.random().toString(16).slice(2),ts:Date.now(),db,hz,note:hz?hzToNote(hz):'--',peakHz:pk.peakHz,active});if(snapshots.length>SNAP_MAX)snapshots=snapshots.slice(snapshots.length-SNAP_MAX);renderSnapshots()}
function startSegment(){if(!running())return;segActive=true;segStartTs=Date.now();segVol=[];segHz=[];segActiveFrames=0;segTotalFrames=0;segmentStart.disabled=true;segmentStop.disabled=false;segmentResult.classList.remove('hidden');segmentResult.textContent=MSG[lang].recording;controls()}
function stopSegment(){if(!segActive)return;segActive=false;segmentStart.disabled=!running();segmentStop.disabled=true;renderSegmentResult()}
function resetAll(){segActive=false;segStartTs=0;segVol=[];segHz=[];segActiveFrames=0;segTotalFrames=0;segmentResult.classList.add('hidden');segmentResult.textContent='';segmentStop.disabled=true;segmentStart.disabled=!running();snapshots=[];renderSnapshots();hideStatus();resetMeter();controls()}
micButton.addEventListener('click',startMic);if(stopMicButton)stopMicButton.addEventListener('click',()=>stopMic());snapshotButton.addEventListener('click',takeSnapshot);segmentStart.addEventListener('click',startSegment);segmentStop.addEventListener('click',stopSegment);resetButton.addEventListener('click',resetAll);clearSnapshotsBtn.addEventListener('click',()=>{if(!snapshots.length)return;if(!clearArmed){clearArmed=true;status(MSG[lang].clearArmed,'info');clearTimeout(clearTimer);clearTimer=setTimeout(()=>{clearArmed=false},3500);return}clearArmed=false;clearTimeout(clearTimer);snapshots=[];renderSnapshots();status(MSG[lang].cleared,'info')});document.querySelectorAll('[data-lang-switch]').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.langSwitch)));window.addEventListener('resize',()=>{if(analyser&&freqData){try{analyser.getByteFrequencyData(freqData);draw(freqData)}catch{}}else resetMeter()});window.addEventListener('pagehide',()=>stopMic({show:false}));window.addEventListener('beforeunload',()=>stopMic({show:false}));snapshotButton.disabled=true;segmentStart.disabled=true;segmentStop.disabled=true;resetButton.classList.add('hidden');resetMeter();renderSnapshots();applyLang(lang);controls();
})();
