const ROOT='/tools/pattern-dictionary/';
const DATA=ROOT+'data/patterns.json';
const PROD=ROOT+'data/production-content.json';
const DICT=ROOT+'data/search-dictionary.json';
let patternsPromise,dictPromise;
const REFERENCE_IDS=new Set(['houndstooth','gingham','tartan','glen-check','argyle','chevron','polka-dot','moroccan-trellis','seigaiha','asanoha','shippo','ichimatsu','kikko','karakusa','damask','arabesque','paisley','leopard-print','ikat','kilim']);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>(s||'').toLowerCase().normalize('NFKC').replace(/[’']/g,"'").replace(/[‐‑‒–—―]/g,'-').replace(/\s+/g,' ').trim();
const MATCH_THRESHOLD=20;
const queryTokens=s=>norm(s).split(/[\s,、。/]+/).filter(Boolean);
function editDistance(a,b){const m=a.length,n=b.length,prev=Array.from({length:n+1},(_,i)=>i),cur=new Array(n+1);for(let i=1;i<=m;i++){cur[0]=i;for(let j=1;j<=n;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=n;j++)prev[j]=cur[j]}return prev[n]}
function nearTypo(a,b){a=norm(a);b=norm(b);if(!a||!b||a===b||Math.min(a.length,b.length)<5||Math.abs(a.length-b.length)>1)return false;if(a.length===b.length){const d=[];for(let i=0;i<a.length;i++)if(a[i]!==b[i])d.push(i);if(d.length===2&&d[1]===d[0]+1&&a[d[0]]===b[d[1]]&&a[d[1]]===b[d[0]])return true}return editDistance(a,b)<=1}
function typoHit(q,p){const qt=queryTokens(q),ct=[p.names?.ja,p.names?.en,...(p.aliases?.ja||[]),...(p.aliases?.en||[])].flatMap(queryTokens);return qt.some(a=>ct.some(b=>nearTypo(a,b)))}
const esc=s=>(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]));
async function patterns(){return patternsPromise||(patternsPromise=Promise.all([fetch(DATA).then(r=>r.json()),fetch(PROD).then(r=>r.json())]).then(([base,prod])=>{const overlays=Object.fromEntries((prod.patterns||[]).map(x=>[x.pattern_id,x]));return base.map(p=>{const o=overlays[p.id]||{};return {...p,...o,id:p.id,names:{...p.names,...(o.names||{})},aliases:{ja:[...new Set([...(p.aliases?.ja||[]),...(o.aliases?.ja||[])])],en:[...new Set([...(p.aliases?.en||[]),...(o.aliases?.en||[])])]},colors:{...p.colors,...(o.colors||{})},description:o.definition||p.description,relationships:p.relationships,search_terms:p.search_terms,families:p.families,motifs:p.motifs,visual:p.visual,uses:p.uses,culture:p.culture}})}))}
async function dict(){return dictPromise||(dictPromise=fetch(DICT).then(r=>r.json()))}
function detailUrl(p,lang){return ROOT+(lang==='en'?'en/':'')+'patterns/'+encodeURIComponent(p.id)+'/'}
function compareUrl(a,b,lang){return ROOT+(lang==='en'?'en/':'')+'compare.html?a='+encodeURIComponent(a)+'&b='+encodeURIComponent(b)}
function patternSvg(p){
  if(REFERENCE_IDS.has(p.id))return ROOT+'assets/reference/'+p.id+'.png';
  const id=p.id, fam=p.families?.[0]||''; let body='';
  if(['houndstooth','chevron'].includes(id))body='<path d="M0 30L30 0l20 20 20-20 30 30-30 30-20-20-20 20z" fill="#111827"/>';
  else if(['gingham','tartan','glen-check','ichimatsu'].includes(id)||fam==='check')body='<rect width="50" height="50" fill="#1f2937"/><rect x="50" y="50" width="50" height="50" fill="#1f2937"/><path d="M50 0V100M0 50H100" stroke="#94a3b8" stroke-width="12" opacity=".55"/>';
  else if(id==='argyle')body='<path d="M50 0L100 50 50 100 0 50z" fill="#334155"/><path d="M0 0L100 100M100 0L0 100" stroke="#cbd5e1" stroke-width="4"/>';
  else if(id==='polka-dot')body='<circle cx="25" cy="25" r="13" fill="#111827"/><circle cx="75" cy="75" r="13" fill="#111827"/>';
  else if(id==='seigaiha')body='<path d="M0 50a50 50 0 0 1 100 0M15 50a35 35 0 0 1 70 0M30 50a20 20 0 0 1 40 0" fill="none" stroke="#1e3a8a" stroke-width="5"/>';
  else if(id==='shippo')body='<circle cx="0" cy="50" r="50" fill="none" stroke="#1e3a8a" stroke-width="4"/><circle cx="100" cy="50" r="50" fill="none" stroke="#1e3a8a" stroke-width="4"/><circle cx="50" cy="0" r="50" fill="none" stroke="#1e3a8a" stroke-width="4"/><circle cx="50" cy="100" r="50" fill="none" stroke="#1e3a8a" stroke-width="4"/>';
  else if(['asanoha','kikko'].includes(id))body='<path d="M50 0L94 25v50L50 100 6 75V25zM50 0v100M6 25l88 50M94 25L6 75" fill="none" stroke="#1e3a8a" stroke-width="4"/>';
  else if(['damask','arabesque','karakusa','moroccan-trellis'].includes(id))body='<path d="M50 7C20 7 20 37 43 47 13 57 25 93 50 87c25 6 37-30 7-40C80 37 80 7 50 7z" fill="none" stroke="#374151" stroke-width="6"/>';
  else if(id==='paisley')body='<path d="M28 15c30 7 47 30 34 56-12 23-47 17-47-7 0-14 10-20 20-29 8-7 7-15-7-20z" fill="none" stroke="#7c2d12" stroke-width="6"/>';
  else if(id==='leopard-print')body='<path d="M12 18c12-12 30-7 28 7-2 12-17 17-27 10-8-5-8-12-1-17zM58 60c8-13 30-10 32 4 2 15-20 22-30 13-7-5-7-12-2-17z" fill="none" stroke="#78350f" stroke-width="8"/><circle cx="72" cy="20" r="7" fill="#78350f"/>';
  else if(id==='ikat')body='<path d="M50 3L90 50 50 97 10 50z" fill="#9a3412"/><path d="M50 15L78 50 50 85 22 50z" fill="#1e3a8a"/>';
  else body='<path d="M0 50H100M50 0V100" stroke="#111827" stroke-width="8"/>';
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><defs><pattern id="p" width="100" height="100" patternUnits="userSpaceOnUse"><rect width="100" height="100" fill="#f8fafc"/>${body}</pattern></defs><rect width="600" height="600" fill="url(#p)"/><rect x="14" y="14" rx="8" width="78" height="36" fill="white" opacity=".94"/><text x="53" y="39" text-anchor="middle" font-family="system-ui,sans-serif" font-size="19" font-weight="700" fill="#b91c1c">DEV</text></svg>`;
  return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)
}
function card(p,lang){return `<article class="pd-card" data-family="${esc(p.families?.[0]||'')}"><a href="${detailUrl(p,lang)}"><div class="pd-thumb"><img loading="lazy" src="${patternSvg(p)}" alt="${esc(p.names[lang])}"></div><div class="pd-card-title">${esc(p.names[lang])}</div><div class="pd-card-sub">${esc(p.names[lang==='ja'?'en':'ja'])}</div>${REFERENCE_IDS.has(p.id)?'':'<div class="pd-dev">DEV PLACEHOLDER</div>'}</a></article>`}
function imageStatus(p,lang){if(REFERENCE_IDS.has(p.id))return `<p class="pd-warning">${lang==='ja'?'1536×1536 PNG Reference Imageは構造レビュー済みです。現在はreviewedで、最終verified前です。':'The 1536×1536 PNG Reference Image has passed structural review. Status: reviewed; final verification is still pending.'}</p>`;return '';}
function bag(p,lang){return norm([p.names?.[lang],p.names?.[lang==='ja'?'en':'ja'],...(p.aliases?.[lang]||[]),...(p.search_terms?.[lang]||[]),...(p.motifs||[]),...(p.families||[]),...(p.visual?.geometry||[]),...(p.visual?.line||[]),...(p.colors?.primary||[]),...(p.uses||[]),...(p.culture||[]),p.term_scope,p.definition?.[lang],...(p.distinguishing_features?.[lang]||[]),...(p.common_uses?.[lang]||[])].join(' '))}
async function interpret(q,lang){const all=await dict(),nq=norm(q),out=[],seen=new Set();for(const l of [lang,lang==='ja'?'en':'ja'])for(const [k,v] of Object.entries(all[l]||{})){const nk=norm(k);if(nq.includes(nk)&&!seen.has(nk)){seen.add(nk);out.push({label:k,...v})}}return out}
async function rank(q,lang,removed=[]){const ps=await patterns(),nq=norm(q),sig=(await interpret(q,lang)).filter(x=>!removed.includes(x.label)),tokens=queryTokens(nq);return {signals:sig,results:ps.map(p=>{let score=0,reasons=[];const add=(n,r)=>{score+=n;if(r&&!reasons.includes(r))reasons.push(r)};const name=norm(p.names[lang]),other=norm(p.names[lang==='ja'?'en':'ja']);if(nq===name)add(100,lang==='ja'?'正式名称':'exact name');if(nq===other)add(70,lang==='ja'?'他言語名':'other language name');for(const a of p.aliases?.[lang]||[]){const na=norm(a);if(nq===na)add(90,lang==='ja'?'別名':'alias');else if(nq.includes(na)||na.includes(nq))add(45,lang==='ja'?'別名':'alias')}for(const t of p.search_terms?.[lang]||[]){const nt=norm(t);if(nq.includes(nt)||nt.includes(nq))add(55,lang==='ja'?'説明語':'descriptive phrase')}if(typoHit(nq,p))add(38,lang==='ja'?'表記ゆれ候補':'possible typo');const b=bag(p,lang);for(const tok of tokens)if(tok.length>1&&b.includes(tok))add(12,tok);for(const x of sig){if((x.ids||[]).includes(p.id))add(72,x.label);if((x.families||[]).some(v=>p.families.includes(v)))add(45,x.label);if((x.colors||[]).some(v=>(p.colors?.primary||[]).includes(v)))add(15,x.label);if((x.culture||[]).some(v=>(p.culture||[]).includes(v)))add(35,x.label);if((x.uses||[]).some(v=>(p.uses||[]).includes(v)))add(25,x.label);for(const c of x.concepts||[])if(b.includes(norm(c)))add(35,x.label)}return{pattern:p,score,reasons}}).sort((a,b)=>b.score-a.score||a.pattern.id.localeCompare(b.pattern.id))}}
function confidence(r){if(!r.length||r[0].score<MATCH_THRESHOLD)return'LOW';const d=r[0].score-(r[1]?.score||0);if(r[0].score>=70&&d>=20)return'HIGH';if(r[0].score>=35)return'MEDIUM';return'LOW'}
async function initHome(lang){const ps=await patterns(),grid=$('#pattern-grid'),count=$('#pattern-count');const render=list=>{grid.innerHTML=list.map(p=>card(p,lang)).join('');count.textContent=lang==='ja'?`${list.length}件`:`${list.length} patterns`};render(ps);$$('[data-family]').forEach(b=>b.onclick=()=>{$$('[data-family]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');render(b.dataset.family?ps.filter(p=>p.families.includes(b.dataset.family)):ps)});const input=$('#q'),box=$('#autocomplete');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=input.value.trim();if(!q){box.hidden=true;return}const r=(await rank(q,lang)).results.filter(x=>x.score>=MATCH_THRESHOLD).slice(0,4);if(!r.length){box.hidden=true;return}box.innerHTML=r.map(({pattern:p})=>`<a class="pd-suggestion" href="${detailUrl(p,lang)}"><img src="${patternSvg(p)}" alt=""><div><strong>${esc(p.names[lang])}</strong><span>${esc(p.names[lang==='ja'?'en':'ja'])}</span></div></a>`).join('');box.hidden=false},140)};document.addEventListener('click',e=>{if(!box.contains(e.target)&&e.target!==input)box.hidden=true})}
async function initSearch(lang){const input=$('#q'),chips=$('#interpret'),out=$('#results'),params=new URLSearchParams(location.search);input.value=params.get('q')||'';let removed=[];async function run(){const q=input.value.trim();if(!q){chips.innerHTML='';out.innerHTML=`<div class="pd-empty">${lang==='ja'?'模様を言葉で説明してください。':'Describe the pattern in words.'}</div>`;return}const rr=await rank(q,lang,removed),vis=rr.results.filter(x=>x.score>=MATCH_THRESHOLD).slice(0,8);chips.innerHTML=rr.signals.filter(s=>!removed.includes(s.label)).map(s=>`<span class="pd-chip">${esc(s.label)}<button type="button" data-r="${esc(s.label)}">×</button></span>`).join('');$$('[data-r]',chips).forEach(b=>b.onclick=()=>{removed.push(b.dataset.r);run()});if(!vis.length){out.innerHTML=`<div class="pd-empty">${lang==='ja'?'一致する模様を特定できませんでした。':'No pattern could be identified.'}</div>`;return}const c=confidence(vis),top=vis[0],p=top.pattern;out.innerHTML=`<p class="pd-note">${c==='LOW'?(lang==='ja'?'一致する模様を特定できませんでした。近い候補を表示しています。':'No confident match. Showing nearby candidates.'):(lang==='ja'?'最も近い候補':'Closest candidate')}</p><section class="pd-top-result"><img src="${patternSvg(p)}" alt=""><div><p class="pd-kicker">${c} confidence</p><h1 class="pd-title">${esc(p.names[lang])}</h1><p class="pd-enname">${esc(p.names[lang==='ja'?'en':'ja'])}</p><div class="pd-match">${top.reasons.slice(0,6).map(r=>`<span>✓ ${esc(r)}</span>`).join('')}</div><p class="pd-copy">${esc(p.description?.[lang]||'')}</p><a class="pd-button" href="${detailUrl(p,lang)}">${lang==='ja'?'詳しく見る':'View details'}</a></div></section><section class="pd-section"><div class="pd-section-head"><h2>${lang==='ja'?'ほかの候補':'Other candidates'}</h2></div><div class="pd-result-list">${vis.slice(1).map(x=>card(x.pattern,lang)).join('')}</div></section>`}$('#search-form').onsubmit=e=>{e.preventDefault();removed=[];history.replaceState(null,'','?q='+encodeURIComponent(input.value));run()};run()}
async function initDetail(lang){const ps=await patterns(),map=Object.fromEntries(ps.map(p=>[p.id,p])),id=document.body.dataset.patternId||new URLSearchParams(location.search).get('id'),p=map[id]||ps[0],rel=[...(p.relationships?.often_confused_with||[]),...(p.relationships?.similar||[])].filter((x,i,a)=>a.indexOf(x)===i).map(x=>map[x]).filter(Boolean),features=p.distinguishing_features?.[lang]||[],uses=p.common_uses?.[lang]||[];document.title=`${p.names[lang]} | Pattern Dictionary | NicheWorks`;$('#detail').innerHTML=`<section class="pd-detail-head"><div><img class="pd-detail-image" src="${patternSvg(p)}" alt=""><p class="pd-warning">${lang==='ja'?'この画像はUI検証用DEVプレースホルダーです。辞典用Reference Imageとして未検証です。':'This image is a DEV placeholder for UI validation, not a verified dictionary Reference Image.'}</p></div><div><p class="pd-kicker">${p.verification_state==='qualified'?'RESEARCHED · QUALIFIED':'RESEARCHED'}</p><h1 class="pd-title">${esc(p.names[lang])}</h1><p class="pd-enname">${esc(p.names[lang==='ja'?'en':'ja'])}</p><div class="pd-tags">${[...p.families,...p.motifs.slice(0,3)].map(x=>`<span class="pd-tag">${esc(x)}</span>`).join('')}</div><p class="pd-copy">${esc(p.definition?.[lang]||p.description?.[lang]||'')}</p><table class="pd-table"><tr><th>${lang==='ja'?'別名':'Aliases'}</th><td>${esc((p.aliases?.[lang]||[]).join(', ')||'—')}</td></tr><tr><th>${lang==='ja'?'用語の範囲':'Term scope'}</th><td>${esc(p.term_scope||'—')}</td></tr><tr><th>${lang==='ja'?'代表色':'Primary colors'}</th><td>${esc(p.colors.primary.join(' + '))}</td></tr><tr><th>${lang==='ja'?'色の扱い':'Color role'}</th><td>${esc(p.colors.color_role)}</td></tr><tr><th>${lang==='ja'?'主な用途':'Common uses'}</th><td>${esc(uses.join(', ')||'—')}</td></tr></table>${rel[0]?`<a class="pd-button secondary" href="${compareUrl(p.id,rel[0].id,lang)}">${lang==='ja'?'似た柄と比較':'Compare with a similar pattern'}</a>`:''}</div></section><section class="pd-section"><div class="pd-section-head"><h2>${lang==='ja'?'見分け方':'How to identify it'}</h2></div><ul class="pd-copy">${features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${p.qualification?.[lang]?`<div class="pd-warning"><strong>${lang==='ja'?'用語上の注意':'Scope note'}</strong><br>${esc(p.qualification[lang])}</div>`:''}</section><section class="pd-section"><div class="pd-section-head"><h2>${lang==='ja'?'似ている・間違えやすい模様':'Similar or commonly confused patterns'}</h2></div><div class="pd-related">${rel.map(x=>card(x,lang)).join('')}</div></section><section class="pd-section"><div class="pd-commerce"><h2>${lang==='ja'?'この柄の商品を探す':'Find products in this pattern'}</h2><p class="pd-note">${lang==='ja'?'Amazonリンクはまだ接続していません。辞典本文とReference Imageの検証後に接続します。':'Amazon links are not connected yet. They will be added after dictionary copy and Reference Images are verified.'}</p></div></section>`;const langLink=$('#lang-link');if(langLink)langLink.href=ROOT+(lang==='ja'?'en/':'')+'patterns/'+encodeURIComponent(p.id)+'/'}
async function initCompare(lang){const ps=await patterns(),map=Object.fromEntries(ps.map(p=>[p.id,p])),q=new URLSearchParams(location.search);let a=map[q.get('a')]||ps[0],b=map[q.get('b')]||ps[1],el=$('#compare');const opts=s=>ps.map(p=>`<option value="${p.id}" ${p.id===s?'selected':''}>${esc(p.names[lang])}</option>`).join('');function render(){el.innerHTML=`<div class="pd-filter-row"><label>${lang==='ja'?'左':'Left'} <select id="cmp-a">${opts(a.id)}</select></label><label>${lang==='ja'?'右':'Right'} <select id="cmp-b">${opts(b.id)}</select></label></div><div class="pd-compare-grid pd-section"><article class="pd-compare-panel"><img src="${patternSvg(a)}" alt=""><h2>${esc(a.names[lang])}</h2></article><article class="pd-compare-panel"><img src="${patternSvg(b)}" alt=""><h2>${esc(b.names[lang])}</h2></article></div><table class="pd-table"><tr><th>${lang==='ja'?'分類':'Family'}</th><td>${esc(a.families.join(', '))}</td><td>${esc(b.families.join(', '))}</td></tr><tr><th>${lang==='ja'?'代表色':'Primary colors'}</th><td>${esc(a.colors.primary.join(' + '))}</td><td>${esc(b.colors.primary.join(' + '))}</td></tr><tr><th>${lang==='ja'?'特徴語':'Visual cues'}</th><td>${esc(a.motifs.join(' / '))}</td><td>${esc(b.motifs.join(' / '))}</td></tr></table>`;$('#cmp-a').onchange=e=>{a=map[e.target.value];sync()};$('#cmp-b').onchange=e=>{b=map[e.target.value];sync()}}function sync(){history.replaceState(null,'',`?a=${a.id}&b=${b.id}`);render()}render()}
const page=document.body.dataset.page,lang=document.documentElement.lang==='en'?'en':'ja';if(page==='home')initHome(lang);if(page==='search')initSearch(lang);if(page==='detail')initDetail(lang);if(page==='compare')initCompare(lang);
