    import fs from "fs";
    import path from "path";
    import type { WPStructureReport } from "./types.js";

    export function generateReportFiles(report: WPStructureReport, outDir: string) {
      const jsonPath = path.join(outDir, "report.json");
      fs.writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf8");

      const htmlPath = path.join(outDir, "report.html");
      fs.writeFileSync(htmlPath, buildHtml(report), "utf8");
    }

    function buildHtml(report: WPStructureReport): string {
      const esc = (v: string) =>
        v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

      const formatBytes = (bytes: number): string => {
        if (!bytes || bytes <= 0) return "0 B";
        const units = ["B", "KB", "MB", "GB", "TB"];
        let i = 0;
        let val = bytes;
        while (val >= 1024 && i < units.length - 1) {
          val /= 1024;
          i++;
        }
        return `${val.toFixed(1)} ${units[i]}`;
      };

      return `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <title>WP Structure Report</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; margin: 20px; line-height: 1.5; }
    h1, h2, h3 { margin-top: 1.4em; }
    table { border-collapse: collapse; width: 100%; margin-top: 0.5em; font-size: 13px; }
    th, td { border: 1px solid #ddd; padding: 4px 6px; text-align: left; }
    th { background: #f5f5f5; }
    .tag { display: inline-block; padding: 2px 6px; margin-right: 4px; border-radius: 4px; background: #eee; font-size: 10px; }
    .small { font-size: 11px; color: #666; }
  </style>
</head>
<body>
  <h1>WordPress 構造解析レポート</h1>
  <div class="small">
    生成日時: ${esc(report.generatedAt)} /
    テーブル接頭辞: <code>${esc(report.tablePrefix)}</code>
  </div>

  <h2>サマリー</h2>
  <ul>
    <li>投稿タイプ数: ${report.postTypes.length}</li>
    <li>タクソノミー数: ${report.taxonomies.length}</li>
    <li>プラグイン数: ${report.plugins.length}</li>
    <li>テーマ数: ${report.themes.length}</li>
    <li>メディア: ${
      report.media
        ? `${report.media.totalFiles} files / ${formatBytes(report.media.totalBytes)}`
        : "wp-content/uploads 未解析"
    }</li>
  </ul>

  <h2>投稿タイプ</h2>
  <table>
    <thead>
      <tr>
        <th>post_type</th>
        <th>総数</th>
        <th>ステータス別</th>
        <th>スラッグ例</th>
      </tr>
    </thead>
    <tbody>
      ${report.postTypes.map(pt => {
        const statuses = Object.entries(pt.byStatus)
          .map(([k, v]) => `<span class="tag">${esc(k)}: ${v}</span>`)
          .join(" ");
        return `<tr>
          <td>${esc(pt.postType)}</td>
          <td>${pt.total}</td>
          <td>${statuses}</td>
          <td>${pt.sampleSlugs.map(esc).join(", ")}</td>
        </tr>`;
      }).join("\n")}
    </tbody>
  </table>

  <h2>カスタムフィールド（上位）</h2>
  <p class="small">使用回数が多い順に最大500件を表示。</p>
  <table>
    <thead>
      <tr>
        <th>meta_key</th>
        <th>総数</th>
        <th>post_type別</th>
      </tr>
    </thead>
    <tbody>
      ${report.metaKeys.map(mk => {
        const pts = Object.entries(mk.postTypes)
          .map(([k, v]) => `<span class="tag">${esc(k)}: ${v}</span>`)
          .join(" ");
        return `<tr>
          <td>${esc(mk.metaKey)}</td>
          <td>${mk.count}</td>
          <td>${pts}</td>
        </tr>`;
      }).join("\n")}
    </tbody>
  </table>

  <h2>タクソノミー</h2>
  <table>
    <thead>
      <tr>
        <th>taxonomy</th>
        <th>terms (概算)</th>
      </tr>
    </thead>
    <tbody>
      ${report.taxonomies.map(tx =>
        `<tr><td>${esc(tx.taxonomy)}</td><td>${tx.terms}</td></tr>`
      ).join("\n")}
    </tbody>
  </table>

  <h2>プラグイン</h2>
  <table>
    <thead>
      <tr><th>ディレクトリ名</th><th>path</th></tr>
    </thead>
    <tbody>
      ${report.plugins.map(p =>
        `<tr><td>${esc(p.name)}</td><td>${esc(p.path)}</td></tr>`
      ).join("\n")}
    </tbody>
  </table>

  <h2>テーマ</h2>
  <table>
    <thead>
      <tr><th>ディレクトリ名</th><th>path</th></tr>
    </thead>
    <tbody>
      ${report.themes.map(t =>
        `<tr><td>${esc(t.name)}</td><td>${esc(t.path)}</td></tr>`
      ).join("\n")}
    </tbody>
  </table>

  ${
    report.media
      ? `<h2>メディア内訳</h2>
  <table>
    <thead>
      <tr><th>拡張子</th><th>件数</th><th>合計サイズ</th></tr>
    </thead>
    <tbody>
      ${Object.entries(report.media.byExt).map(([ext, info]) =>
        `<tr>
          <td>${esc(ext)}</td>
          <td>${info.count}</td>
          <td>${formatBytes(info.bytes)}</td>
        </tr>`
      ).join("\n")}
    </tbody>
  </table>`
      : ""
  }

  <hr />
  <p class="small">
    Generated by WP Structure Analyzer (NicheWorks MVP). このレポートはローカル解析専用であり、DBやファイルは外部送信されません。
  </p>
</body>
</html>`;
    }
