// Canonical symbol set: JIS L 0001:2024 overview published by the Consumer Affairs Agency.
// Scope: symbols shown on the CAA page for labels used in Japan from 2024-08-20 onward.
// `jis` is the symbol number used in the official tables. Do not add convenience duplicates.
window.SYMBOLS = [
  // Washing — Table 1
  { id:"jis-190", jis:"190", cat:"wash", m:{temp:95},
    ja:{summary:"95℃まで・通常洗濯", detail:"液温95℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 95°C", detail:"Normal machine washing is permitted up to 95°C."} },
  { id:"jis-170", jis:"170", cat:"wash", m:{temp:70},
    ja:{summary:"70℃まで・通常洗濯", detail:"液温70℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 70°C", detail:"Normal machine washing is permitted up to 70°C."} },
  { id:"jis-160", jis:"160", cat:"wash", m:{temp:60},
    ja:{summary:"60℃まで・通常洗濯", detail:"液温60℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 60°C", detail:"Normal machine washing is permitted up to 60°C."} },
  { id:"jis-161", jis:"161", cat:"wash", m:{temp:60,underline:1},
    ja:{summary:"60℃まで・弱い洗濯", detail:"液温60℃を限度として、洗濯機で弱い洗濯処理ができます。"},
    en:{summary:"Gentle wash up to 60°C", detail:"A mild machine-wash process is permitted up to 60°C."} },
  { id:"jis-150", jis:"150", cat:"wash", m:{temp:50},
    ja:{summary:"50℃まで・通常洗濯", detail:"液温50℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 50°C", detail:"Normal machine washing is permitted up to 50°C."} },
  { id:"jis-151", jis:"151", cat:"wash", m:{temp:50,underline:1},
    ja:{summary:"50℃まで・弱い洗濯", detail:"液温50℃を限度として、洗濯機で弱い洗濯処理ができます。"},
    en:{summary:"Gentle wash up to 50°C", detail:"A mild machine-wash process is permitted up to 50°C."} },
  { id:"jis-140", jis:"140", cat:"wash", m:{temp:40},
    ja:{summary:"40℃まで・通常洗濯", detail:"液温40℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 40°C", detail:"Normal machine washing is permitted up to 40°C."} },
  { id:"jis-141", jis:"141", cat:"wash", m:{temp:40,underline:1},
    ja:{summary:"40℃まで・弱い洗濯", detail:"液温40℃を限度として、洗濯機で弱い洗濯処理ができます。"},
    en:{summary:"Gentle wash up to 40°C", detail:"A mild machine-wash process is permitted up to 40°C."} },
  { id:"jis-142", jis:"142", cat:"wash", m:{temp:40,underline:2},
    ja:{summary:"40℃まで・非常に弱い洗濯", detail:"液温40℃を限度として、洗濯機で非常に弱い洗濯処理ができます。"},
    en:{summary:"Very gentle wash up to 40°C", detail:"A very mild machine-wash process is permitted up to 40°C."} },
  { id:"jis-130", jis:"130", cat:"wash", m:{temp:30},
    ja:{summary:"30℃まで・通常洗濯", detail:"液温30℃を限度として、洗濯機で通常の洗濯処理ができます。"},
    en:{summary:"Machine wash up to 30°C", detail:"Normal machine washing is permitted up to 30°C."} },
  { id:"jis-131", jis:"131", cat:"wash", m:{temp:30,underline:1},
    ja:{summary:"30℃まで・弱い洗濯", detail:"液温30℃を限度として、洗濯機で弱い洗濯処理ができます。"},
    en:{summary:"Gentle wash up to 30°C", detail:"A mild machine-wash process is permitted up to 30°C."} },
  { id:"jis-132", jis:"132", cat:"wash", m:{temp:30,underline:2},
    ja:{summary:"30℃まで・非常に弱い洗濯", detail:"液温30℃を限度として、洗濯機で非常に弱い洗濯処理ができます。"},
    en:{summary:"Very gentle wash up to 30°C", detail:"A very mild machine-wash process is permitted up to 30°C."} },
  { id:"jis-110", jis:"110", cat:"wash", m:{hand:true,underline:1},
    ja:{summary:"40℃まで・手洗い", detail:"液温40℃を限度として、手洗いによる洗濯処理ができます。"},
    en:{summary:"Hand wash up to 40°C", detail:"Hand washing is permitted up to 40°C."} },
  { id:"jis-111", jis:"111", cat:"wash", m:{hand:true,underline:2},
    ja:{summary:"30℃まで・手洗い", detail:"液温30℃を限度として、手洗いによる洗濯処理ができます。"},
    en:{summary:"Hand wash up to 30°C", detail:"Hand washing is permitted up to 30°C."} },
  { id:"jis-100", jis:"100", cat:"wash", m:{no:true},
    ja:{summary:"家庭での洗濯禁止", detail:"家庭での洗濯処理はできません。"},
    en:{summary:"Do not wash", detail:"Washing is not permitted."} },

  // Bleaching — Table 2
  { id:"jis-220", jis:"220", cat:"bleach", m:{},
    ja:{summary:"塩素系・酸素系漂白可", detail:"塩素系および酸素系漂白剤による漂白処理ができます。"},
    en:{summary:"Chlorine and oxygen bleach allowed", detail:"Bleaching with chlorine or oxygen bleach is permitted."} },
  { id:"jis-210", jis:"210", cat:"bleach", m:{nonchlorine:true},
    ja:{summary:"酸素系漂白のみ可", detail:"酸素系漂白剤は使用できますが、塩素系漂白剤は使用できません。"},
    en:{summary:"Oxygen bleach only", detail:"Oxygen bleach is permitted; chlorine bleach is not permitted."} },
  { id:"jis-200", jis:"200", cat:"bleach", m:{no:true},
    ja:{summary:"漂白禁止", detail:"漂白処理はできません。"},
    en:{summary:"Do not bleach", detail:"Bleaching is not permitted."} },

  // Drying — Table 3: tumble drying
  { id:"jis-320", jis:"320", cat:"dry", m:{tumble:true,dots:2},
    ja:{summary:"タンブル乾燥可・高温", detail:"タンブル乾燥ができ、排気温度の上限は80℃です。"},
    en:{summary:"Tumble dry, high heat", detail:"Tumble drying is permitted with an exhaust-temperature maximum of 80°C."} },
  { id:"jis-310", jis:"310", cat:"dry", m:{tumble:true,dots:1},
    ja:{summary:"タンブル乾燥可・低温", detail:"タンブル乾燥ができ、排気温度の上限は60℃です。"},
    en:{summary:"Tumble dry, low heat", detail:"Tumble drying is permitted with an exhaust-temperature maximum of 60°C."} },
  { id:"jis-300", jis:"300", cat:"dry", m:{tumble:true,no:true},
    ja:{summary:"タンブル乾燥禁止", detail:"洗濯処理後のタンブル乾燥はできません。"},
    en:{summary:"Do not tumble dry", detail:"Tumble drying after washing is not permitted."} },

  // Drying — Table 4: natural drying
  { id:"jis-440", jis:"440", cat:"dry", m:{verticalLines:1},
    ja:{summary:"つり干し", detail:"脱水後、つり干し乾燥が適しています。"},
    en:{summary:"Line dry", detail:"Line drying after water extraction is recommended."} },
  { id:"jis-445", jis:"445", cat:"dry", m:{verticalLines:1,shade:true},
    ja:{summary:"日陰でつり干し", detail:"脱水後、日陰でのつり干し乾燥が適しています。"},
    en:{summary:"Line dry in shade", detail:"Line drying in the shade after water extraction is recommended."} },
  { id:"jis-430", jis:"430", cat:"dry", m:{verticalLines:2},
    ja:{summary:"ぬれつり干し", detail:"脱水せず、ぬれたままつり干し乾燥するのが適しています。"},
    en:{summary:"Drip line dry", detail:"Line drying without water extraction is recommended."} },
  { id:"jis-435", jis:"435", cat:"dry", m:{verticalLines:2,shade:true},
    ja:{summary:"日陰でぬれつり干し", detail:"脱水せず、日陰でぬれたままつり干し乾燥するのが適しています。"},
    en:{summary:"Drip line dry in shade", detail:"Line drying in shade without water extraction is recommended."} },
  { id:"jis-420", jis:"420", cat:"dry", m:{horizontalLines:1},
    ja:{summary:"平干し", detail:"脱水後、平干し乾燥が適しています。"},
    en:{summary:"Dry flat", detail:"Flat drying after water extraction is recommended."} },
  { id:"jis-425", jis:"425", cat:"dry", m:{horizontalLines:1,shade:true},
    ja:{summary:"日陰で平干し", detail:"脱水後、日陰での平干し乾燥が適しています。"},
    en:{summary:"Dry flat in shade", detail:"Flat drying in the shade after water extraction is recommended."} },
  { id:"jis-410", jis:"410", cat:"dry", m:{horizontalLines:2},
    ja:{summary:"ぬれ平干し", detail:"脱水せず、ぬれたまま平干し乾燥するのが適しています。"},
    en:{summary:"Drip dry flat", detail:"Flat drying without water extraction is recommended."} },
  { id:"jis-415", jis:"415", cat:"dry", m:{horizontalLines:2,shade:true},
    ja:{summary:"日陰でぬれ平干し", detail:"脱水せず、日陰でぬれたまま平干し乾燥するのが適しています。"},
    en:{summary:"Drip dry flat in shade", detail:"Flat drying in shade without water extraction is recommended."} },

  // Ironing — Table 5
  { id:"jis-530", jis:"530", cat:"iron", m:{dots:3},
    ja:{summary:"アイロン・210℃まで", detail:"底面温度210℃を限度としてアイロン仕上げ処理ができます。"},
    en:{summary:"Iron up to 210°C", detail:"Ironing is permitted with a sole-plate temperature up to 210°C."} },
  { id:"jis-520", jis:"520", cat:"iron", m:{dots:2},
    ja:{summary:"アイロン・160℃まで", detail:"底面温度160℃を限度としてアイロン仕上げ処理ができます。"},
    en:{summary:"Iron up to 160°C", detail:"Ironing is permitted with a sole-plate temperature up to 160°C."} },
  { id:"jis-510", jis:"510", cat:"iron", m:{dots:1},
    ja:{summary:"アイロン・120℃まで", detail:"底面温度120℃を限度としてアイロン仕上げ処理ができます。"},
    en:{summary:"Iron up to 120°C", detail:"Ironing is permitted with a sole-plate temperature up to 120°C."} },
  { id:"jis-511", jis:"511", cat:"iron", m:{dots:1,steamNo:true},
    ja:{summary:"120℃まで・スチーム禁止", detail:"底面温度120℃を限度として、スチームなしでアイロン仕上げ処理ができます。スチームは損傷を引き起こす可能性があります。"},
    en:{summary:"Iron up to 120°C, no steam", detail:"Ironing without steam is permitted up to 120°C. Steam may cause irreversible damage."} },
  { id:"jis-500", jis:"500", cat:"iron", m:{no:true},
    ja:{summary:"アイロン禁止", detail:"アイロン仕上げ処理はできません。"},
    en:{summary:"Do not iron", detail:"Ironing is not permitted."} },

  // Professional dry cleaning — Table 6
  { id:"jis-620", jis:"620", cat:"dryclean", m:{code:"P"},
    ja:{summary:"ドライクリーニング P・通常", detail:"P記号で認められる溶剤による、通常のドライクリーニング処理ができます。"},
    en:{summary:"Professional dry clean P, normal", detail:"Normal professional dry cleaning using solvents permitted for symbol P is allowed."} },
  { id:"jis-621", jis:"621", cat:"dryclean", m:{code:"P",underline:1},
    ja:{summary:"ドライクリーニング P・弱い", detail:"P記号で認められる溶剤による、弱いドライクリーニング処理ができます。"},
    en:{summary:"Professional dry clean P, gentle", detail:"A mild professional dry-cleaning process using solvents permitted for symbol P is allowed."} },
  { id:"jis-610", jis:"610", cat:"dryclean", m:{code:"F"},
    ja:{summary:"ドライクリーニング F・通常", detail:"F記号で認められる溶剤による、通常のドライクリーニング処理ができます。"},
    en:{summary:"Professional dry clean F, normal", detail:"Normal professional dry cleaning using solvents permitted for symbol F is allowed."} },
  { id:"jis-611", jis:"611", cat:"dryclean", m:{code:"F",underline:1},
    ja:{summary:"ドライクリーニング F・弱い", detail:"F記号で認められる溶剤による、弱いドライクリーニング処理ができます。"},
    en:{summary:"Professional dry clean F, gentle", detail:"A mild professional dry-cleaning process using solvents permitted for symbol F is allowed."} },
  { id:"jis-600", jis:"600", cat:"dryclean", m:{no:true},
    ja:{summary:"ドライクリーニング禁止", detail:"ドライクリーニング処理はできません。"},
    en:{summary:"Do not dry clean", detail:"Professional dry cleaning is not permitted."} },

  // Professional wet cleaning — Table 7
  { id:"jis-710", jis:"710", cat:"dryclean", m:{code:"W"},
    ja:{summary:"ウエットクリーニング W・通常", detail:"プロによる通常のウエットクリーニング処理ができます。家庭での水洗いとは別の表示です。"},
    en:{summary:"Professional wet clean W, normal", detail:"Normal professional wet cleaning is permitted. This is not the same as home washing."} },
  { id:"jis-711", jis:"711", cat:"dryclean", m:{code:"W",underline:1},
    ja:{summary:"ウエットクリーニング W・弱い", detail:"プロによる弱いウエットクリーニング処理ができます。"},
    en:{summary:"Professional wet clean W, gentle", detail:"A mild professional wet-cleaning process is permitted."} },
  { id:"jis-712", jis:"712", cat:"dryclean", m:{code:"W",underline:2},
    ja:{summary:"ウエットクリーニング W・非常に弱い", detail:"プロによる非常に弱いウエットクリーニング処理ができます。"},
    en:{summary:"Professional wet clean W, very gentle", detail:"A very mild professional wet-cleaning process is permitted."} },
  { id:"jis-700", jis:"700", cat:"dryclean", m:{code:"W",no:true},
    ja:{summary:"ウエットクリーニング禁止", detail:"ウエットクリーニング処理はできません。"},
    en:{summary:"Do not wet clean", detail:"Professional wet cleaning is not permitted."} }
];
